### ISSUE TITLE
Slow query in hangfire.job

### ISSUE THREAD

**Issue by jwu-au** [sergeyzwezdin/Hangfire.Mongo#104]
Hi,

I'm running hangfire in production using mLab which reports slow query in hangfire.job collection. Just wondering we can do anything about it? please see below:
```
namespace
hangfire.hangfire.job
aggregate command
{"$match":{"StateName":{"$ne":"<val>"}}}
{"$group":{"_id":{"StateName":"$StateName"},"StateName":{"$first":"$StateName"},"Count":{"$sum":"<val>"}}}
```
![image](https://user-images.githubusercontent.com/833961/30353812-c9c204b4-986b-11e7-890e-d1b04300bb2d.png)

Thank you for helping.

**Comment by mathieukempe** [comment]
Also the number of documents in the collection is around 10000, so not massive.
We use mongodb 3.0

**Comment by MarLoe** [comment]
@jwu-au & @mathieukempe, thankyou for your feedback. We will look into this and see if we can improve.
Please remember that we love pull requests. So if you feel that you can optimizing our queries or in any other way improve Hangfire.Monge, we would appreciate it.

**Comment by mathieukempe** [comment]
Sure we will look how we can improve as well

**Comment by mathieukempe** [comment]
Considering there is an index on StateName 
Looking at the query, using 
```json
{"$match":{"StateName":{"$nin": ["Deleted","Failed"]}}}
```

Might be better than using $ne : null

**Comment by MarLoe** [comment]
Will be a part of release 0.5.5

**Comment by MarLoe** [comment]
Btw, thank you for the PR 😃
