### ISSUE TITLE
Job State is wrong in mongodb

### ISSUE THREAD

**Issue by AlexanderNaiden** [sergeyzwezdin/Hangfire.Mongo#106]
After connected to mongodb from asp.net core application, I see wrong job state in hangfire dashboard.   Why job state is Enqueued, if it was done? But if I use as storage - sql server then state is Succeeded and it is correct. See my screen by link https://yadi.sk/i/VYrWndJZ3N7DwW.

**Comment by MarLoe** [comment]
@AlexanderNaiden, thanks for your feedback - and sorry for the late reply.

I'll try to find the time to look into this. In the meantime: We love PR :)

**Comment by gottscj** [comment]
@AlexanderNaiden,

Sorry for the late reply. This should be fixed #119

**Comment by MarLoe** [comment]
Will be a part of the 0.5.6 release
