### ISSUE TITLE
Replace polling with publish-subscribe

### ISSUE THREAD

**Issue by maleet** [sergeyzwezdin/Hangfire.Mongo#11]
Any plans on replacing polling with something more real-time like described here:
http://tugdualgrall.blogspot.fr/2015/01/how-to-create-pubsub-application-with.html

I'm not a mongodb specialist so I'm just googling around some alternatives for hangfire with MSSQL+MSMQ usage. I need instant job handling so polling don't fit.

**Comment by sergeyzwezdin** [comment]
No plans for the moment. May be in future.

**Comment by runxc1** [comment]
Would doing something like this http://blog.mongodb.org/post/29495793738/pubsub-with-mongodb perform better?

**Comment by sergeyzwezdin** [comment]
@runxc1 thanks for the link. May be later.

**Comment by MarLoe** [comment]
@maleet, @runxc1 
A "Tailable Cursor" solution is in the making. Expect it to be a part of the 0.6.0 release.
Check out the [signal](https://github.com/sergeyzwezdin/Hangfire.Mongo/tree/signal) branch - this where the work happens.

**Comment by gottscj** [comment]
I can finally close this one. in 0.6.0 we are using tailable cursors to signal job queue and distributed lock. enjoy
