### ISSUE TITLE
Element 'Reason' not found Exception from GetRecurringJobs()

### ISSUE THREAD

**Issue by janmagnet** [sergeyzwezdin/Hangfire.Mongo#110]
Similar to issue #85 where the `CamelCaseElementNameConvention` caused problems, there is an issue with registering `new IgnoreIfNullConvention(true)` in the MongoDB convention registry.

After any recurring job has executed once, this call:

`var recurringJobs = JobStorage.Current.GetConnection().GetRecurringJobs();`

Throws the following exception:
> System.Collections.Generic.KeyNotFoundException: Element 'Reason' not found.
>    at MongoDB.Bson.BsonDocument.get_Item(String name)
>    at Hangfire.Mongo.MongoConnection.GetStateData(String jobId)
>    at Hangfire.Storage.StorageConnectionExtensions.GetRecurringJobDtos(IStorageConnection connection, IEnumerable`1 ids)

And the dashboard fails when accessing the "Recurring Jobs" tab. Jobs will continue to run without a problem.

The problem is caused by this setup, which is needed by our application:
`var pack = new ConventionPack { new IgnoreIfNullConvention(true) };
ConventionRegistry.Register("ApplicationConventions", pack, t => true);`

Hangfire.Core 1.16.17
Hangfire.Mongo 0.5.4

I suspect other conventions could cause similar problems. Due to the convention registry being global it applies to all types that do not explicitly register a `BsonClassMap`, as well as those that do register a class map using automapping (`BsonClassMap.AutoMap()`).

**Comment by MarLoe** [comment]
@janmagnet, thank you for your feedback. I'll look into this and your PR. As we always say: We love PRs. I'll try to get this into the next release 0.5.5

**Comment by MarLoe** [comment]
Ready for 0.5.5
