### ISSUE TITLE
Hangfire dashboard logs sorted in ascending order

### ISSUE THREAD

**Issue by yudevit** [sergeyzwezdin/Hangfire.Mongo#116]
I'm using the latest version of Hangifre (1.6.17) and Hangfire.Mongo (0.5.5) and I'm having troubles sorting the dashboard's failed jobs logs.

Currently they're sorted in ascending order where the oldest logs/failed jobs appear in the first page of results. Obviously I'd like to have them sorted in descending order so that the recent ones appear in the first page.

I was wondering whether it's possible to change the order of the logs? If yes, how?

Any help is greatly appreciated!

**Comment by cemusta** [comment]
this issue also appears in the older versions like (0.30)...

**Comment by gottscj** [comment]
@yudevit, @cemusta

Sorry for the delayed reply. 
Hangfire.Mongo implements Hangfire API's. Hangfire does have a Monitoring API, but it does not support "ordering"
https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/Storage/IMonitoringApi.cs

If you can get @odinserj to update the API, we will support it shortly hereafter. :)

**Comment by cemusta** [comment]
@gottscj,

Thanks for info,

default ordering is wrong can't you just sort the logs newest first (descending) by default? 

Custom sort ordering is not necessary but default ordering should be Date ordered by descending

**Comment by gottscj** [comment]
@cemusta,

You are right! Sorry. I'll make sure it's fixed for next release.

**Comment by yudevit** [comment]
@cemusta 

That's exactly the issue, simply sorting logs by the date will do.

@gottscj 

From what I can see the current sorting is done for each page rather than on a whole logs data set. I end up having logs from **seven** days ago at the bottom of the third then at the bottom of the fourth page again - it's pretty mixed up. It'd be great if you could sort all the logs before applying the pagination.

Thanks for the time and efforts invested to maintain this lib!

**Comment by gottscj** [comment]
Guys,

Sorry for the late reply, #118 should solve this issue.

Thanks

**Comment by MarLoe** [comment]
Will be a part of the 0.5.6 release
