### ISSUE TITLE
Not enqueueing jobs after large load

### ISSUE THREAD

**Issue by lukasroberts** [sergeyzwezdin/Hangfire.Mongo#12]
Hi there

I have ran into a problem whilst using the MongoDB driver. When i queue 250 jobs at once with a maximum number of retries of two after a few minutes, all the jobs fail to be enqueued and remain in the scheduled state.

The Hangfire.Mongo version is 0.2.1, and runs fine otherwise. From a guess it looks like the database cannot handle the large load of job states transitioning. I tried the same scenario with a Postgres database and it worked fine, so it does lead me to believe that this is a database level issue with Mongo.

Do you know anything around this, and possible ways to prevent it from happening?

**Comment by sergeyzwezdin** [comment]
Hi @lukasroberts 
There is another issue #10 - I guess it's all related. I will take a look what to do with that.

**Comment by lukasroberts** [comment]
I'm not sure it is related, as i am using the older non async version. I just updated Hangfire to 1.5.0 and it does not seem to be putting anywhere near as much load on Mongo. Potentially this was a HangFire issue?

**Comment by sergeyzwezdin** [comment]
I don't know. @odinserj - what do you think?

**Comment by odinserj** [comment]
Sorry for being late 😞 In Hangfire 1.5.0, there was a fix for a problem with `TaskCanceledException` thrown when processing a background job. Such an exception caused workers to stop one after another until background job server is restarted.

**Comment by gofix** [comment]
https://discuss.hangfire.io/t/mongodb-storage-driver-not-enqueueing-jobs-after-large-load/1398/2?u=gofix

We're using 1.5.8 and are still experiencing this :(

**Comment by odinserj** [comment]
Try to [add logging](http://docs.hangfire.io/en/latest/configuration/configuring-logging.html), this may show some useful information. 

We can also investigate thread stacks to see where Hangfire is stuck. I've recently created a small tool, [`stdump`](https://github.com/odinserj/stdump) that attaches to a process in a non-invasive way and shows all the stack traces. Here is the [downloads page](https://github.com/odinserj/stdump/releases).

```
stdump process_id > output.txt
```

**Comment by gottscj** [comment]
@gofix,

Can I close this? Did you get a chance to try some of the new releases? @MarLoe is currently contributing to this repo, so the bug should be solved.

Thanks!

**Comment by gofix** [comment]
Issue may be closed, using newer version now

**Comment by gottscj** [comment]
thanks. closing...
