### ISSUE TITLE
Cannot resolve symbol `UseMongoStorage`

### ISSUE THREAD

**Issue by kkorus** [sergeyzwezdin/Hangfire.Mongo#146]
I'm using ASP.NET WebApi 2 and in Startup I want to configure Hangfire with MongoDB, but on this line:

` GlobalConfiguration.Configuration.UseMongoStorage`

I'm having error `Cannot resolve symbol UseMongoStorage`

Hangfire.Mongo version 0.5.11

**Comment by gottscj** [comment]
@kkorus,

Hangfire's GlobalConfiguration is named the same as System.Web.Http.GlobalConfiguration class.
Please verify you are in fact using _Hangfire.GlobalConfiguration_ and not _System.Web.Http.GlobalConfiguration_

Thanks,
Jonas

**Comment by kkorus** [comment]
@gottscj Yep, you were right, I was using wrong `GlobalConfiguration`
