### ISSUE TITLE
How to disable deletion of expired jobs?

### ISSUE THREAD

**Issue by kkorus** [sergeyzwezdin/Hangfire.Mongo#148]
If I set 
```csharp
MongoStorageOptions.JobExpirationCheckInterval = TimeSpan.FromMilliseconds(0);
```
will this disable deletion of expired jobs?

**Comment by gottscj** [comment]
We use a WaitHandle when checking for expired jobs. You can use settings below to wait indefinetly.

This will however also stop deletion of associated job data.

`var migrationOptions = new MongoStorageOptions
            {
                JobExpirationCheckInterval = TimeSpan.FromMilliseconds(-1)
            };`

**Comment by kkorus** [comment]
Thanks @gottscj , if I would like to deleted job related data that by job id, which collection I should consider?

**Comment by kkorus** [comment]
I think I have found a solution, which I want to test:

```csharp
    public class MyCustomFiler : IApplyStateFilter
    {
        public void OnStateApplied(ApplyStateContext context, IWriteOnlyTransaction transaction)
        {
            if (context.NewState is DeletedState)
            {
                context.JobExpirationTimeout = TimeSpan.FromMinutes(1);
            }

            if (context.NewState is SucceededState)
            {
                context.JobExpirationTimeout = TimeSpan.MaxValue;
            }
        }

        public void OnStateUnapplied(ApplyStateContext context, IWriteOnlyTransaction transaction)
        {
        }
    }
```

**Comment by gottscj** [comment]
@kkorus ,

glad to hear it. Let us know if it works out. :)
