### ISSUE TITLE
DisableConcurrentExecution seems not to work

### ISSUE THREAD

**Issue by Thieund** [sergeyzwezdin/Hangfire.Mongo#15]
Hi there,
I'm using DisableConcurrentExecution(600) to disable concurrency. I've tested it with thread.delay(10') but the tasks still run in parallel. I'm wonder if Hangfire.Mongo supports this attribute ?

**Comment by sergeyzwezdin** [comment]
Hi @Thieund 
Will check later, thanks!

**Comment by MarLoe** [comment]
I observe this issue as well. I believe it is related to a faulty implemented MongoDistributedLock. I have made a pull request with a fix: https://github.com/sergeyzwezdin/Hangfire.Mongo/pull/40

**Comment by MarLoe** [comment]
The Hangfire attribute DisableConcurrentExecution relies heavily on the implementation of JobStorageConnection.AcquireDistributedLock 
With the merge of pull request #40 that fixes MongoDistributedLock I believe this issue is resolved.
