### ISSUE TITLE
Growing number of enqueued jobs that don't get processed for some reason

### ISSUE THREAD

**Issue by provanguard** [sergeyzwezdin/Hangfire.Mongo#153]
After updating to release 0.5.12 with the new schema etc., I have noticed that on the environment running the updated version, there is a steadily growing number of enqueued jobs that do not get processed for some reason. At the moment there is 32 of them. I found all of them in the jobGraph collection and all of them have only one state in the StateHistory array, namely state 0 Enqueued. I cannot find any indication of reason for this, no failed jobs. Please kindly help with solving this problem.

```
{ 
    "_id" : ObjectId("5be0d5fd06b1e90001fbeba6"), 
    "_t" : [
        "BaseJobDto", 
        "ExpiringJobDto", 
        "JobDto"
    ], 
    "ExpireAt" : null, 
    "StateName" : "Enqueued", 
    "InvocationData" : "{\"Type\":\"xxx.xxx.Jobs.RefreshxxxJob, xxxCore, Version=1.0.193.0, Culture=neutral, PublicKeyToken=null\",\"Method\":\"Work\",\"ParameterTypes\":\"[]\",\"Arguments\":\"[]\"}", 
    "Arguments" : "[]", 
    "Parameters" : {
        "RecurringJobId" : "\"RefreshxxxJob\"", 
        "CurrentCulture" : "\"\"", 
        "CurrentUICulture" : "\"\""
    }, 
    "StateHistory" : [
        {
            "Name" : "Enqueued", 
            "Reason" : "Triggered by recurring job scheduler", 
            "CreatedAt" : ISODate("2018-11-05T23:45:01.195+0000"), 
            "Data" : {
                "EnqueuedAt" : "2018-11-05T23:45:01.0712814Z", 
                "Queue" : "default"
            }
        }
    ], 
    "CreatedAt" : ISODate("2018-11-05T23:45:01.071+0000")
}
```

**Comment by gottscj** [comment]
@provanguard,

I cannot reproduce this in our sample environment. Please try to add the build in "ColouredConsoleLogProvider" to your hangfire configuration to log potential errors.
http://docs.hangfire.io/en/latest/configuration/configuring-logging.html

Im not sure how you have setup your queues, but it could look like you 
It could look like there is not a hangfire background server configured to process the "default" queue?

**Comment by provanguard** [comment]
There are thousands of jobs executions processed. All settings are as before version 0.5.12. But there is this small percentage of jobs that are queued but not processed.

**Comment by provanguard** [comment]
Could this be related to the timeout errors I mentioned in another issue?

**Comment by gottscj** [comment]
@provanguard,

Perhaps, 
Try to enable logging and run it locally and see if you can reproduce. I will be happy to help, but I need more information

**Comment by provanguard** [comment]
As for the logging, I have an aspnet core web api application with serilog and microsoft DI. Logging is configured so that all methods, including those invoked as background jobs by hangfire can log their operations. But the hangfire itself does not produce any logs.

I have also found this issue about logging, still unresolved:
https://github.com/HangfireIO/Hangfire/issues/1089

Can you clarify which logging you are interested in and how it can be enabled in my application?

**Comment by gottscj** [comment]
@provanguard,

Sorry for the late reply, I have been traveling.
please follow the provided link for how to enable hangfire logging.
http://docs.hangfire.io/en/latest/configuration/configuring-logging.html

**Comment by provanguard** [comment]
@gottscj After deleting the collections for hangfire mongo, and restarting the app to create them again, the issue of some jobs not being processed has disappeared. This could have also been related to additional settings added to the mongo client to fix occasional timeouts.
