### ISSUE TITLE
HashDto in db still has Field instead of Fields

### ISSUE THREAD

**Issue by dmikov** [sergeyzwezdin/Hangfire.Mongo#156]
FormatException: Element 'Field' does not match any field or property of class Hangfire.Mongo.Dto.HashDto.
 
We have migrate no backup strategy enabled. However after upgrading to 5.12 we are getting the above error. I looked at commits it looks like it has v 13 in migrate even though the component itself is only 12. Could that be the issue that Field is not updated to Fields?

**Comment by gottscj** [comment]
@dmikov,

 Yikes! its a bug. 
All those objects should have been deleted by the migration step. If you can. Drop the jobs db. else, you can maunally delete all dto's using this command in the mongo shell:

db['hangfire.jobGraph'].deleteMany({ "_t.3": "HashDto", $and: [ { "Field": { $exists: true } } ] })

schema v13 is correct.
I'll make sure to correct this in next release. Also looks like our migration tests needs some love.

**Comment by gottscj** [comment]
@dmikov,

The safest will be to run the script in the mongo shell. 
Depending on how you use Hangfire queues, migration (IMO) are only needed if you:

1) Have Fire-And-Forget jobs queued, but not executed yet. They will be lost if you drop the DB.
2) Have scheduled jobs queued, but not executed yet. also lost.
2) Use the information provided in the MonitoringAPI. things such as SuccededCount will be lost

I cannot guarantee you wont loose data.

**Comment by gottscj** [comment]
Fixed in v0.5.13
