### ISSUE TITLE
Monitoring issue - jobs not shown

### ISSUE THREAD

**Issue by Thieund** [sergeyzwezdin/Hangfire.Mongo#16]
Hi Sergey,
I experienced the problem that some jobs are shown only when the big page size (500) is selected.
I think in the GetJobs function, the .Select((data, i) => new { Index = i + 1, Data = data }) should be called after the .Where(...) filter...
Pls correct me if I'm wrong.

**Comment by sergeyzwezdin** [comment]
Hi @Thieund 
Yep, it's very possible. Let me check, and I'll come back.

**Comment by Thieund** [comment]
Hi Sergey,
FYI (or you already knew): What I wrote here is exactly the same as pull request #14.

**Comment by sergeyzwezdin** [comment]
@Thieund so, #14 fixes this, right?

**Comment by Thieund** [comment]
Yes, that's right Sergey.

**Comment by sergeyzwezdin** [comment]
Thanks.
