### ISSUE TITLE
Requeued job (manual or autoretry) are always shown as "aborted" when using multiple hangfire servers

### ISSUE THREAD

**Issue by scadorel** [sergeyzwezdin/Hangfire.Mongo#167]
Hello,

We're using multiple hangfire servers. A requeued job might be processed by another server; but when it does, the job is incorrectly shown as "aborted" in the UI because the serverId is an old one. The "Started" date is also incorrect (showing first run start date instead of current one).
I've tested with SQL server storage, and the issue doesn't appear. It seems specific to mongo storage.
Only the monitoring API is impacted. ProcessingState is properly filled with correct values.

<img width="447" alt="hangfiremongo_requeue_abort" src="https://user-images.githubusercontent.com/2738119/50488743-4711b300-0a04-11e9-9810-54e77367c7c9.png">

After looking in code, the issue is located on those lines:
https://github.com/sergeyzwezdin/Hangfire.Mongo/blob/508db7f0ccb5da82663a1b652ccfd72a4d7fff27/src/Hangfire.Mongo/MongoMonitoringApi.cs#L449
https://github.com/sergeyzwezdin/Hangfire.Mongo/blob/508db7f0ccb5da82663a1b652ccfd72a4d7fff27/src/Hangfire.Mongo/MongoMonitoringApi.cs#L501

The least recent state is taken from history instead of taking the most recent. Changing the FirstOrDefault() by LastOrDefault() fixed the issue.

I've tested the fix above with latest hangfire.mongo, and it works ok.
I can provide a PR if you want.

**Comment by gottscj** [comment]
@scadorel,
That would be great! 
If you could add a unit test and branch off 0.5.14, it would be awesome!

I will be releasing 0.5.14 first thing in the new year.

Thanks!

**Comment by scadorel** [comment]
@gottscj,
Sure, I'll try to provide the PR tomorrow.
Thanks.

**Comment by scadorel** [comment]
Thanks @gottscj 
I've updated with latest 0.5.14 and the issue is fixed. Closing.
