### ISSUE TITLE
Dashboard, top menu, Recurring Jobs count is 0 on release 0.5.14.

### ISSUE THREAD

**Issue by provanguard** [sergeyzwezdin/Hangfire.Mongo#173]
After updating to the latest release (0.5.14), I have noticed that the counter for Recurring Jobs in the Hangfire Dashboard always shows 0, even though there are jobs listed on the page and they seem to be executing. Is this related to code changes in the latest release?

**Comment by gottscj** [comment]
@provanguard,

Its a bug introduced in 0.5.14, I missed updating a query for Recurring-Jobs which now uses a composite key.
We were also missing a unit test for this, so this is added in the PR

Thanks

**Comment by gottscj** [comment]
@provanguard,

I have released v0.5.15, please go ahead and close this issue, when you have confirmed its been fixed.

Thanks!

**Comment by provanguard** [comment]
The count has been fixed in the new release.
