### ISSUE TITLE
GetAllItemsFromSet truncated values on release 0.5.14

### ISSUE THREAD

**Issue by scadorel** [sergeyzwezdin/Hangfire.Mongo#175]
Hi,

With the latest release (0.5.14), the GetAllItemsFromSet truncates values which contains ":". Seems related to changes done for #168, the format in db has changed.
I'm using Hangfire.Console which relies on the set feature. JSON values are saved in a set (multiple usage of ":"). When retrieved by the extension, values are truncated resulting in JSON parse exception, breaking the extension.
This is not a migration, as I can reproduce the issue with a clean db as well.

Here is a small unit test to replicate the issue. "11:22" is expected for the first value (behavior in 0.5.13); "22" is returned instead (behavior in 0.5.14).

```
        [Fact, CleanDatabase]
        public void GetAllItemsFromSet_ReturnsAllItems_WithCorrectValues()
        {
            using (var t = this._connection.CreateWriteTransaction())
            {
                t.AddToSet("some-set", "11:22");
                t.AddToSet("some-set", "33");
                t.Commit();
            }

            // Act
            var result = _connection.GetAllItemsFromSet("some-set");

            // Assert
            Assert.Equal(new[] { "11:22", "33" }, result);
        }
```

**Comment by gottscj** [comment]
@scadorel,

Thanks for the unit test. 
I SetDto actually still has a "Value" field which should have been used.

I will supply a fix shortly

**Comment by gottscj** [comment]
@scadorel,

I have released v0.5.15, please go ahead and close this issue if you can confirm its been fixed.

Thanks!

**Comment by provanguard** [comment]
The count is fixed now.
By the way, what is the current list of collections that the Hangfire.Mongo should create and use? During the recent migrations, I have noticed that the number of collections created is changing. Sometimes some collections are not created on some environments.
With the 0.5.15 I now have 4 collections in my dev database:
- hangfire.jobGraph
- hangfire.locks
- hangfire.schema
- hangfire.server

My prod db, which still runs on an older version, has one more collection comparing to the dev db:
- hangfire.signal

My impression is that migration or even fresh creation is not completely stable. So I am now manually deleting the collections on each new version of the Hangfire.Mongo package. But still, sometimes, I am getting different number of collections created.

**Comment by gottscj** [comment]
@provanguard,

The collections are correct in 0.5.15.

We are working on adding a tailable collection (signal) so polling could be avoided. accidentally that work creeped into the master branch (and a release) and the collection has been part of the system in the past couple of releases, until now where I explicitly remove it in schema 16.

We havent been good enough to test the migrations, and there has been more bugs in that system than needed. 
We had some unfortunate bugs for a clean migration (fixed) which should solved. and going forward we will write tests for all migration steps. something we failed to do before.

All this work is being done after work and after kids has been tugged, so we need all the help and patience we can get. :)

We are very interested in this being a success, so all the feedback you provide is awesome!

Thanks!

**Comment by provanguard** [comment]
Great, you can count on my input, if I notice any issues :)

**Comment by scadorel** [comment]
@gottscj Still need to do something else but I'll try to do the test today and let you know. Thanks :)

**Comment by scadorel** [comment]
Works like a charm. Thanks for the fix. 👍
