### ISSUE TITLE
Broke app on startup

### ISSUE THREAD

**Issue by sowa111111** [sergeyzwezdin/Hangfire.Mongo#179]
If MongoDB is unavailable when the application is started, then Hangfire throws the exception `Could not place a lock on the resource 'Migrate'` and the app can't run. 
It would be nice if this `critical for hangfire` issue did not break the application.

**Comment by gottscj** [comment]
@sowa111111,

I agree the error could be more descriptive. 
I think we will still throw an exception if we cant connect to the DB. So your application needs to catch that if that is a valid startup condition for you.
We can add tests verifying the connection. We will try to add that for next release.


Thanks,
Jonas

**Comment by kcragin** [comment]
@sowa111111 @gottscj what causes this issue? I've setup Hangfire.Mongo for the first time and can't connect. I am using the same connection string and database that other parts of the service can connect to without problem.

**Comment by sowa111111** [comment]
Hello

We are using hangfire. Mongo lib. And today we did some load testing, and
get horrible results on it. Looks like the reason is 'looks'. Maybe you
have any tips how configure Mongo connection to impruve performance.

пн, 18 февр. 2019 г., 18:18 Jonas Gottschau <notifications@github.com>:

**Comment by gottscj** [comment]
@sowa111111 ,

Did you mean 'locks' ?

Hangfire controls when lock are acquired and why. 
How did you load test and what results were you expecting? what is your configuration?

Its possible to start multiple instances of Hangfire. That could perhaps be a solution?

**Comment by sowa111111** [comment]
Yeah, sorry. I mean locks😊

Basically, we have we api service with hangfire. The service responsobility
to schedule, update and delete jobs in hangfire. We did the load testing
with special framework, which simulate hundreats request from multiple
users. We got really low results, and big response time. With additional
logging we found that the reason looks like 'locks' in database.

We use the same configuration like in README file.

Yeah, we thought about creating multipli hangfire instances inside web api
application.

чт, 14 мар. 2019 г., 18:54 Jonas Gottschau <notifications@github.com>:

**Comment by gottscj** [comment]
using our sample code in combination with Parallel.Foreach I can enqueue 1000 jobs in approx 450ms in debug  mode on my old macbook.

I did not try to interleave with deleting or updating jobs. Im not sure what your use case is, but if you need faster im nor sure this is the framework you need. If you need distributed work, you could look into NetMq which should be very fast.


`var sw = Stopwatch.StartNew();
            Parallel.ForEach(Enumerable.Range(0, id), i =>
            {
                var index = i;
                BackgroundJob.Enqueue(() => PrintToDebug($@"Hangfire fire-and-forget task started ({index}) - {Guid.NewGuid()}"));
                
            });
            Console.WriteLine($"Enqueue {id} jobs in {sw.ElapsedMilliseconds}ms");`

**Comment by KyleCraviotto** [comment]
My team ran into this same issue this week after upgrading 0.5.15
It caused a lot of heartache, until we realized it wasn't able to 'get a lock' on the temporary collection migrationLock because our database admins have turned on the admin command notablescan https://docs.mongodb.com/manual/reference/parameters/#param.notablescan

The solution ended up creating indexes for ExpireAt and Resource.
It would probably be good to create indexes for these so that even those that have notablescan turned on would successfully start the application.

**Comment by gottscj** [comment]
@KyleCraviotto,

Thanks for the input. I have rewritten the migration lock to not use the distributed lock used by hangfire as this collection might need migration also.

The migration lock will use a known "Id" a single index for locking the migrations. Hopefully this would give you a better experience when using the migrations

**Comment by gottscj** [comment]
I added an optional connection check (defaults to true). please let me know if it doesnt work as expected
