### ISSUE TITLE
Plans on upgrade to Hangfire 1.5?

### ISSUE THREAD

**Issue by runxc1** [sergeyzwezdin/Hangfire.Mongo#18]
I was looking to upgrade this to Hangfire 1.5 as that is what an application I am building is already running and it looks like a number of the interfaces have changed.   Has anyone started looking at that as it looks to be less trivial.

**Comment by sergeyzwezdin** [comment]
Yes, I'm under investigation of this, but still no deadlines though.
I will let you know once it done.

**Comment by sergeyzwezdin** [comment]
Done in `v0.2.3`.
