### ISSUE TITLE
error when trying to connect mongodb on host only ?

### ISSUE THREAD

**Issue by ahmedamen** [sergeyzwezdin/Hangfire.Mongo#181]
Hi
i have and asp core app i try to use hangfire to do some tasks, **it works fine on my windows develop pc** , but when i have add purplish to host (digitalocean) with **Ubuntu 18.04** i got this error

> An exception of type 'Hangfire.Mongo.DistributedLock.MongoDistributedLockException' occurred in Unknown Module. but was not handled in user code
Could not place a lock on the resource 'Migrate': Check inner exception for details.

> An error occurred while starting the application.
TimeoutException: A timeout occured after 30000ms selecting a server using CompositeServerSelector{ Selectors = MongoDB.Driver.MongoClient+AreSessionsSupportedServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : "2", ConnectionMode : "Automatic", Type : "Unknown", State : "Disconnected", Servers : [{ ServerId: "{ ClusterId : 2, EndPoint : "84.16.244.66:27017" }", EndPoint: "84.16.244.66:27017", State: "Disconnected", Type: "Unknown", HeartbeatException: "MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server. ---> MongoDB.Driver.MongoAuthenticationException: Unable to authenticate using sasl protocol mechanism SCRAM-SHA-1. ---> MongoDB.Driver.MongoCommandException: Command saslStart failed: Authentication failed..
at MongoDB.Driver.Core.WireProtocol.CommandUsingQueryMessageWireProtocol`1.ProcessReply(ConnectionId connectionId, ReplyMessage`1 reply)
at MongoDB.Driver.Core.WireProtocol.CommandUsingQueryMessageWireProtocol`1.ExecuteAsync(IConnection connection, CancellationToken cancellationToken)
at MongoDB.Driver.Core.Authentication.SaslAuthenticator.AuthenticateAsync(IConnection connection, ConnectionDescription description, CancellationToken cancellationToken)
--- End of inner exception stack trace ---

> MongoDistributedLockException: Could not place a lock on the resource 'Migrate': Check inner exception for details.
Hangfire.Mongo.DistributedLock.MongoDistributedLock.Acquire(TimeSpan timeout)
Hangfire.Mongo.DistributedLock.MongoDistributedLock..ctor(string resource, TimeSpan timeout, IMongoCollection<DistributedLockDto> locks, MongoStorageOptions storageOptions)
Hangfire.Mongo.Migration.MongoMigrationManager..ctor(MongoStorageOptions storageOptions, HangfireDbContext dbContext)
Hangfire.Mongo.MongoStorage..ctor(MongoClientSettings mongoClientSettings, string databaseName, MongoStorageOptions storageOptions)
Hangfire.Mongo.MongoBootstrapperConfigurationExtensions.UseMongoStorage(IGlobalConfiguration configuration, string connectionString, string databaseName)
SAL125.Web.Startup+<>c.<ConfigureServices>b__4_0(IGlobalConfiguration x) in Startup.cs
+
            services.AddHangfire(x => x.UseMongoStorage("mongodb://ahmed:xxxxxxx@84.16.244.66:27017","mydb"));
Hangfire.HangfireServiceCollectionExtensions+<>c__DisplayClass0_0.<AddHangfire>b__9(IServiceProvider serviceProvider)
Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable<Parameter> parameters)
Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable<Parameter> parameters)

i don't know how i can solve that, or what i must do to make it works online ?

**Comment by ahmedamen** [comment]
any help ?

**Comment by gottscj** [comment]
@ahmedamen,

Looking at the error message it seems you are missing some authentication:


: An exception occurred while opening a connection to the server. ---> MongoDB.Driver.MongoAuthenticationException: Unable to authenticate using sasl protocol mechanism SCRAM-SHA-1. ---> MongoDB.Driver.MongoCommandException: Command saslStart failed: Authentication failed..

**Comment by ahmedamen** [comment]
> @ahmedamen,
> 
> Looking at the error message it seems you are missing some authentication:
> 
> : An exception occurred while opening a connection to the server. ---> MongoDB.Driver.MongoAuthenticationException: Unable to authenticate using sasl protocol mechanism SCRAM-SHA-1. ---> MongoDB.Driver.MongoCommandException: Command saslStart failed: Authentication failed..

but i can use same connection to connect to db using mongoboster or mongo compas

> mongodb://myusername:mypassword@serverip:27017

so can i got help for that please ?

**Comment by gottscj** [comment]
@ahmedamen,

Could you try the overload taking the MongoClientSettings.FromConnectionString and check what the credentials look like?

Is this a problem you are seeing with Hangfire.Mongo or can you connect using the Mongo C# driver at all?

**Comment by gottscj** [comment]
@ahmedamen,

Did you solve your problem? Then please close this issue. :)

**Comment by ahmedamen** [comment]
Solved

**Comment by gottscj** [comment]
@ahmedamen,

Glad to hear it. :)
If its not too sensitive information, it would be great to hear how you solved, it so others having the same issue could benefit from that information.

Thanks!

**Comment by ahmedamen** [comment]
> mongodb://myusername:mypassword@serverip:27017/**databasename**
