### ISSUE TITLE
Hangfire 1.7.0

### ISSUE THREAD

**Issue by EngelenH** [sergeyzwezdin/Hangfire.Mongo#182]
With the release of Hangfire 1.7.0 I am wondering if there is any impact (as there is also some breaking changes and data changes) for Hangfire.Mongo.

And if there is what the expected timetable is for a new version (note I just ask so I know if I should plan the upgrade on my end already or postpone until a later date).

Cheer,
Hans

**Comment by gottscj** [comment]
@EngelenH,

Im planning to release 0.6.0 late next week.

That will be targeting Hangfire 1.7.0. There are some breaking changes in the hangfire api, but it shouldnt be necessary to do a migration to support that. 
0.6.0 will also introduce a tailable collection for signaling jobs enqueued and locks released. 

Br

**Comment by gottscj** [comment]
Referencing Hangfire.Core 1.7.1 and latest mongo driver in 0.6.0, please let me know if you have any issues.
