### ISSUE TITLE
Allow user to supply preconfigured MongoClient

### ISSUE THREAD

**Issue by avonheimburg** [sergeyzwezdin/Hangfire.Mongo#199]
The MongoDB-C#-Client-Documentation states that it is best practice to use a single MongoClient instance for the entire application. If the app which runs hangfire also needs an independent connection to the same MongoDB server, however, we end up with two instances: The MongoClient instance used by Hangfire.Mongo and the instance used by the rest of the app.

It would be great if, instead of just the MongoClientSettings, one could simply provide a preconfigured IMongoClient-instance to the UseMongoStorage()-Extension. That would also make it easier to centralize the MongoClient-configuration.

**Comment by avonheimburg** [comment]
... in addition, apparently, Hangfire.Mongo opens quite a few connections. Sharing the MongoClient-Instance would help with that, too

**Comment by gottscj** [comment]
@avonheimburg, @nicholasb90,

I'll take a look. A PR would also be greatly appreciated. :)
