### ISSUE TITLE
Lower # of "active" workers than worker count with long running jobs in 0.6.0

### ISSUE THREAD

**Issue by zbartl** [sergeyzwezdin/Hangfire.Mongo#206]
After upgrading to `0.6.0` we've started to see some strange behavior with the number of "active" workers (i.e. those processing jobs) not matching the worker count for each server whenever a significant number (> worker count) of long running jobs hits hangfire at once:
![Screen Shot 2019-09-17 at 1 29 30 PM](https://user-images.githubusercontent.com/5209490/65082360-5ad2c000-d96b-11e9-9a9a-e99180c460fc.png)

This appears to be related to the addition of the `JobQueueSemaphore` in `0.6.0` where the non-"active" workers will effectively wait until the semaphore count comes back to 0 before un-blocking and continuing as normal. 

I've attached a `TRACE` level log below where you can see:

- 20 workers come online (lines 1-40)
- 2 of the workers manage to grab long running jobs and decrement the semaphore to from `1` to `0` (lines 83 and 87)
- the semaphore count rises from 0 to 98 (lines 92-298)
- ...and the rest of the workers wait for the 2 initial workers to slowly make their way through the enqueued jobs (lines 408 / 409)

[hangfire-0_6_0-trace.log](https://github.com/sergeyzwezdin/Hangfire.Mongo/files/3623662/hangfire-0_6_0-trace.log)

if any additional logs are needed I'm more than happy to provide them

**Comment by zbartl** [comment]
Interestingly enough we are now seeing the completely opposite happen in a test environment where the # of "active" workers exploded beyond the worker count:

![2019-09-18_09-28-38](https://user-images.githubusercontent.com/5209490/65169014-552cb700-da0b-11e9-9b9b-c4007bf083e3.png)

**Comment by gottscj** [comment]
@zbartl,

yikes! thanks for the log. Let me try to figure out whats going on

**Comment by gottscj** [comment]
@zbartl,

could you elaborate a bit on what your setup looks like? how many servers, queues, etc.

**Comment by zbartl** [comment]
Sure, our local / testing environments are fairly plain:

- a single Api docker container with a shared "notifications" and server specific "x_web_12345" queue
- a single Tasks docker container with a shared "default" and server specific "x_tasks_12345" queue

effectively every enqueued job you see in the screenshots above is going to be in the "default" queue for our single Tasks server to work through (this is best seen in the first screenshot)

the server specific queues are only used in a very small number of startup-style scenarios and notifications should not be seeing much action in these scenarios

**Comment by gottscj** [comment]
@zbartl,

Looking into the log you provided. it seems that there is a lot of jobs being enqueued, but it doesnt look like they are being processed. Would you be able to try 0.6.3? There is a bug in 0.6.0 where DistributedLock is not handling concurrency correctly: #188

thanks

**Comment by zbartl** [comment]
Did try `0.6.2` and `0.6.3` yesterday, no luck there either.

**Comment by gottscj** [comment]
@zbartl,

just to clarify.

You have two hangfire servers. both are listening to "notifications" and "default" queues?

**Comment by zbartl** [comment]
- only api / web hangfire servers listen to "notifications"
  - nothing really going on here that's relevant to the scenarios above
- only tasks hangfire servers listen to "default"
  - this is where we're seeing the odd behavior with either too few or too many workers

in the screenshots above you can see "Servers (2)" at the top of the Hangfire Dashboard, one of those is an api / web (mostly idle) and one is a tasks

**Comment by zbartl** [comment]
@gottscj I'm attempting to dig into `JobQueueSemaphore` to try to explain what I'm seeing with the semaphore counts in the trace logs, but I'm not sure I fully understand it's purpose.

From what I'm seeing:

1. new jobs are enqueued and the semaphore is `Release`ed once
2. each worker attempts to `FetchNextJob`, we check all queues and then `Wait(0)` the semaphore
3. if we successfully fetched a job we return and process (?)
3. this is where I lose the thread a bit, particularly around the call to  `JobQueueSemaphore.WaitAny` if we didn't fetch a job in steps 2/3

Do you mind going over this class a bit and what these semaphores are being used for / controlling? My prior experience here is fairly limited to use cases closer to the example here: https://docs.microsoft.com/en-us/dotnet/api/system.threading.semaphoreslim?view=netframework-4.8

**Comment by zbartl** [comment]
@gottscj Awesome, thanks! I'd hoped to be able to assist more but I appreciate your explanation. 

Just gave your `0.6.4` branch a try locally and it looks like all workers are active:

[hangfire-0_6_4-test.log](https://github.com/sergeyzwezdin/Hangfire.Mongo/files/3632838/hangfire-0_6_4-test.log)

**Comment by gottscj** [comment]
@zbartl,

thanks for trying out 0.6.4 branch! In the end of the log it doesnt seem like jobs are being processed else they are falling behind? But seems correct to you?

**Comment by zbartl** [comment]
@gottscj 

So sorry for the delay in getting back to you.

Those jobs all take about a minute or so to complete so once all 20 workers are working and the semaphore count rises well above 1 that should just be a normal back up of `Enqueued` jobs. I would say that `0.6.4` seems a sound fix to the original issue I was seeing and this issue can be closed. Thank you!

**Comment by gottscj** [comment]
@zbartl,

Thank you for the help. I released Hangfire.Mongo 0.6.4. it should be available on nuget.org now
