### ISSUE TITLE
Successful job deletion

### ISSUE THREAD

**Issue by lukasroberts** [sergeyzwezdin/Hangfire.Mongo#22]
Was just wondering if this driver deletes successful jobs once they are complete? Currently this doesn't seem to be the case as my success list grows to a massive value (over 1 million)

From what I've researched this is meant to be the default behaviour as shown here https://discuss.hangfire.io/t/how-to-configure-the-retention-time-of-job/34

**Comment by sergeyzwezdin** [comment]
Thank you for your feedback. Planned to be fixed in next version.

**Comment by lukasroberts** [comment]
What would this involve from an implementation perspective? Would it be possible for me to fork a copy and get started on it?

**Comment by sergeyzwezdin** [comment]
@lukasroberts I'm not sure yet regarding what exactly need to be fixed - need to investigate this. If you can take a look on this it would be very helpful for sure, so feel free to do that :-)

**Comment by lukasroberts** [comment]
After some investigation, it appears that the ExpirationManager does indeed fire but only at application startup. after this it does not run anymore. What would be the best approach to make this the case?

**Comment by sergeyzwezdin** [comment]
it might be helpful to check how it's implemented for SQL Server storage.
just check references where is `ExpirationManager` called in that storage and ensure it's called in same place for Mongo :-)

**Comment by lukasroberts** [comment]
I couldn't notice any difference and i think it is actually running fine after logging the expiration manager
