### ISSUE TITLE
InvisibilityTimeout should not be obsolete (yet)

### ISSUE THREAD

**Issue by ffMathy** [sergeyzwezdin/Hangfire.Mongo#220]
The reason is that there is no alternative, although Hangfire already has an alternative, I think it's called SlidingInvisibilityTimeout.

**Comment by gottscj** [comment]
@ffMathy,

Thanks, I wasnt aware of the new configuration option in Hangfire. Let me check what it does and why its needed.

thanks!

**Comment by gottscj** [comment]
@ffMathy,

SlidingInvisibilityTimeout is doing the same thing we are doing, but users can opt out if the value is null. I will update Hangfire.Mongo's "InvisibilityTimeout" property to be nullable and opt out if not set.

**Comment by ffMathy** [comment]
That sounds great!

**Comment by rgmills** [comment]
@gottscj Hi, I was looking into this, it doesn't look like there is any code in the storage provider that pushes out the `FetchedAt` value to prevent it from falling into the InvisibilityTimeout threshold.  I'm not terribly familiar with the source code, so I may have missed it.  Would you consider adding it natively or exposing a method on MongoStorage?

**Comment by gottscj** [comment]
@rgmills,

sorry I missed your comment. Im not sure I understand your use case. could you elaborate a bit?

Thanks!

**Comment by rgmills** [comment]
Hey @gottscj ,

No worries! The goal is some jobs have a nondeterministic run time and any predefined InvisibilityTimeout may be insufficient.  In our use case, we sync some data from a 3rd party.  However the 3rd party doesn't have an API to capture deltas so it ends up being a full enumeration.  Depending on the amount of data this can take awhile.

From what I remember seeing in the SqlStorage provider, there is a concept of sliding the InvisibilityTimeout by monitoring the job and pushing out the `FetchedAt` value such that it doesn't timeout.

I've worked around it by doing something like:

```csharp
            var connection = PerformContext.Storage.GetConnection();
            var field = connection.GetType().GetFields(BindingFlags.Instance | BindingFlags.NonPublic).FirstOrDefault(x => x.FieldType == typeof(HangfireDbContext));
            var context = (HangfireDbContext)field.GetValue(connection);

            // Hangfire.MongoDB stores a record separate from the job that controls queueing
            // Fetch that document and use for subsequent updates.
            if (_queueRecordId == null)
            {
                var document = await context.JobGraph.OfType<JobQueueDto>().AsQueryable()
                    .Where(x => x.JobId == ObjectId.Parse(PerformContext.BackgroundJob.Id))
                    .OrderByDescending(x => x.FetchedAt)
                    .FirstOrDefaultAsync();

                _queueRecordId = document.Id;
            }

            var update = Builders<JobQueueDto>.Update.Set(x => x.FetchedAt, DateTime.UtcNow);
            var result = await context.JobGraph.OfType<JobQueueDto>().UpdateOneAsync(x => x.Id == _queueRecordId.Value, update);
```

**Comment by gottscj** [comment]
@rgmills,

hopefully in v0.7.11 that should be possible to do by using the new MongoFactory class or override some of the functionality. everything should inheritable and all public functions are virtual so you can use your own implementation. You can configure everything in the MongoStorageOptions

**Comment by rgmills** [comment]
Ah ok cool, thanks @gottscj  I'll take a look!

**Comment by rgmills** [comment]
Looks like this covers our use-case, thanks @gottscj

**Comment by gottscj** [comment]
fixed
