### ISSUE TITLE
MongoDB WriteConcern

### ISSUE THREAD

**Issue by billfinch** [sergeyzwezdin/Hangfire.Mongo#225]
Can you confirm the write concern setting for the Hangfire.Mongo Driver?  

We use the default WriteConcern Primary in our environment, and it appears that HangFire is using Majority, which causes issues in our current geo-clustered replica set, and is also problematic in our MongoDB Atlas development clusters.

Is there a way to force WriteConcern Primary on the driver?

**Comment by gottscj** [comment]
@billfinch,

We provide different overloads for the MongoStorage instance and hangfire IGlobalConfiguration interface.

You can optionally provide your own MongoClient instance or MongoClientSettings:

 ```csharp
services.AddHangfire(config =>
            {
                var mongoUrlBuilder = new MongoUrlBuilder("mongodb://localhost/my-hangfire-mongo-db");
                var mongoClient = new MongoClient(mongoUrlBuilder.ToMongoUrl());
                
                var storageOptions = new MongoStorageOptions();
                config.UseMongoStorage(mongoClient, mongoUrlBuilder.DatabaseName, storageOptions);
            });

    ```

**Comment by gottscj** [comment]
check out all the options here:

https://github.com/sergeyzwezdin/Hangfire.Mongo/blob/master/src/Hangfire.Mongo/MongoBootstrapperConfigurationExtensions.cs

Br,

**Comment by gottscj** [comment]
@billfinch,

Did this solve your issue?

**Comment by gottscj** [comment]
closing du to inactivity
