### ISSUE TITLE
when hangfire run in docker cpu 97% 

### ISSUE THREAD

**Issue by song0320** [sergeyzwezdin/Hangfire.Mongo#228]
hi,
my code run with docker cpu 97%,but with out docker it's fine, any one can help me
Hangfire.AspNetCore 1.7.9
Hangfire.Mongo 0.6.6
Hangfire.RecurringJobExtensions 1.1.6
asp.net core 3.1
my code:

**ConfigureServices:**

 services.AddHangfire(configuration => {

                var storageOptions = new MongoStorageOptions
                {
                    MigrationOptions = new MongoMigrationOptions {
                        Strategy = MongoMigrationStrategy.Drop
                    }
                };

                configuration.UseMongoStorage(Configuration.GetValue<string>("HangfireStorage"), "Hangfire_DataWatcher", storageOptions);
                configuration.UseFilter(new NotReentryServerHangfireFilter());
            });
            services.AddHangfireServer();

   **Configure:**

   var options = new BackgroundJobServerOptions
            {
                SchedulePollingInterval = TimeSpan.FromSeconds(1)
            };
            app.UseHangfireServer(options);
            app.UseHangfireDashboard("/task", new DashboardOptions()
            {
                Authorization = new[] { new CustomAuthorizeFilter() }
            });

**Comment by song0320** [comment]
may be some thing else

**Comment by gottscj** [comment]
@song0320,

You dont need to set the polling interval to 1s. We use a tailable collection to notify servers that jobs are enqueued. latency should be ~5ms.
I would recommend you to keep it at 15s
Hope you figured it out
