### ISSUE TITLE
Allow setting of Mongo Shard Key

### ISSUE THREAD

**Issue by darrenhull** [sergeyzwezdin/Hangfire.Mongo#230]
There is currently no way to extend this to allow a shard key to be set. Really we just need a way to extend all of the models with say ShardKey  and then a way to set that dynamically through some sort of filter. similar to how the Hangfire filters work.

Also because of the way most things are either internal or sealed it is making it impossible to extend.

**Comment by gottscj** [comment]
@darrenhull,

What would you need me to do, to enable your use-case?

Thanks

**Comment by darrenhull** [comment]
Hi @gottscj,

Thanks for replying when using sharded collections with MongoDb you have to specify the property that is used as the shard key and every document that is inserted needs to have the shard key set. All queries to the database must use this shard key to update the data. You are still able to query the data without the shard key though 

What I need to be able to do is attach a property to the document that is saved to the data. Something like "tenantKey": "client1", then when a document is updated in the db it should also use the tenant key that has been set.

so something like: 

db.getCollection("hangfire.jobGraph").update({ _id: ObjectId("5e8447d202c122857c8be6ee"),TenantKey:"Client1" }, {
    $set: {
        "ExpireAt": ISODate("2020-04-02T08:50:43.352+01:00"),
        "StateName": "Succeeded"
    }
})


So essentially we need to be able to:

1. Define the name of the shard property to be used against all documents
2. Set a value for the shard property that may or may not be different per document.
3. Ensure shard property is set when a document is added or updated.
4. Have the ability to query jobs per shard

Thanks

**Comment by gottscj** [comment]
@darrenhull,

I havent forgotten about you. Im just struggling to make ends meet when working from home and having to home-school two kids also.

I am looking into possible solutions

**Comment by darrenhull** [comment]
Yes I’m in the same predicament at the moment, two young kids and working from home. :-(

Let me know if I can help at all.

**Comment by gottscj** [comment]
@darrenhull,

Im planning to do the following changes:

- Make "MongoConnection" public
- Make "HangfireDbContext" a public readonly property on "MongoConnection"
- Make "MongoClient" and IMongoDatabase" instances public readonly on "HangfireDbContext"

This should enable you to do basically anything you like using the attribute filters.

What do you think?
Thanks

**Comment by gottscj** [comment]
@darrenhull,

I created PR. https://github.com/sergeyzwezdin/Hangfire.Mongo/pull/238

Let me know if it works for you.

**Comment by gottscj** [comment]
v0.7.11 should be extendable to meet your needs. Please let me know if I missed something or I can help out. 
If you have a custom setup it would be great as PR also.
