### ISSUE TITLE
documentation outdated

### ISSUE THREAD

**Issue by kavhad** [sergeyzwezdin/Hangfire.Mongo#246]
The information in the documentation advicing how to setup hangfire for asp.net core apps is not consistent with main hangfire project documentation. 

You propose using the `app.UseHangfireserver()` to start the hangfire-server process, but the main project docs the following code example is given for setup of hangfire server:

```
public void ConfigureServices(IServiceCollection services)
{
    // Add Hangfire services.
    services.AddHangfire(configuration => configuration
        .SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
        .UseSimpleAssemblyNameTypeSerializer()
        .UseRecommendedSerializerSettings()
        .UseSqlServerStorage(Configuration.GetConnectionString("HangfireConnection"), new SqlServerStorageOptions
        {
            CommandBatchMaxTimeout = TimeSpan.FromMinutes(5),
            SlidingInvisibilityTimeout = TimeSpan.FromMinutes(5),
            QueuePollInterval = TimeSpan.Zero,
            UseRecommendedIsolationLevel = true,
            DisableGlobalLocks = true
        }));

    // Add the processing server as IHostedService
    services.AddHangfireServer();

    // Add framework services.
    services.AddMvc();
}
```

The method adviced by your doc actually caused a bug in our application after we started migrating from .Net Core 2.2 to 3.1. The root cause is unclear but it only seem to occur since we have multiple webhosts in same process one for running hangfire server another for dashboard, and it only occured in 3.1 for us and seemed to cause incorrect IoC-container by the hangfire-server process. The bug did not occur when using method proposed in the main project documents.

**Comment by gottscj** [comment]
@kavhad,

I agree it could be better, I will update it so its more clear.

The 

`app.UseHangfireserver()`

is for ASP.NET (non-Core). I have not documentet the use IHostedServer which should be used in ASP.NET Core. 

I will update immediately.

**Comment by kavhad** [comment]
Great thanks for the quick update.
