### ISSUE TITLE
Nuget feed contains version 1.0.0, which is detected as latest stable in Visual Studio

### ISSUE THREAD

**Issue by provanguard** [sergeyzwezdin/Hangfire.Mongo#249]
Is it intentional that there is a version 1.0.0 present in the nuget feed, published in October 2019?

**Comment by gottscj** [comment]
@provanguard,

Thanks!

I am not able to find the offending package version. What am I missing?

**Comment by provanguard** [comment]
@gottscj  Your comment got me thinking and after a quick check, it looks like the 1.0.0 package version got somehow cached on our internal nuget server. It is not listed when I select the public nuget server as a source. Thanks !

By the way, there is a new version of Hangfire available now. Is it a good practice to always wait for your package to get the updated version before updating the Hangfire packages?

**Comment by gottscj** [comment]
Phew!

There shouldnt be a problem updating the Hangfire.Core package. The only caveat though would be if @odinserj added breaking changes to the new release, which it might look like.

Im planning to merge PR #247 and create a new release supporting the new Hangfire.Core package soon though. :)

**Comment by provanguard** [comment]
Thanks again!

**Comment by odinserj** [comment]
I'm trying hard to avoid any breaking changes within the same major version, and I doubt there are any of them when talking about Hangfire.MongoDB package. Extension packages should target the lowest possible version of Hangfire.Core to avoid any possible dependency locks, where some package requires one version, and another package requires another version, and there's no way to satisfy all the requirements.

All the issues with latest versions originate from NuGet client, and once I've seen a way to install the highest possible dependency version by default, but can't found anything except this article – https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio#install-and-update-options

**Comment by gottscj** [comment]
Thanks @odinserj
