### ISSUE TITLE
UseMongoStorage

### ISSUE THREAD

**Issue by wa926talent** [sergeyzwezdin/Hangfire.Mongo#252]
System.InvalidOperationException:“Could not complete migration. Never acquired lock within allowed time: 00:01:00
Either another server did not complete the migration or migration was abruptly interrupted
If migration has been interrupted you need to manually delete 'hangfire.migrationLock' and start again.”

**Comment by gottscj** [comment]
@wa926talent,

Please add some more information. Tell me about your setup, steps to reproduce. what did you try? etc?

**Comment by wa926talent** [comment]
.net core 3.1  Mongodb 4.4.0

**Comment by gottscj** [comment]
closing due to lack of info and seems stale
