### ISSUE TITLE
CollectionMongoBackupStrategy throws authentication error when bypassDocumentValidation permission not granted to mongo user

### ISSUE THREAD

**Issue by twgraham** [sergeyzwezdin/Hangfire.Mongo#253]
I came across an issue when upgrading from 0.6.6 to 0.7.12 - using the new `CollectionMongoBackupStrategy` caused my app to crash on Startup because mongo would throw an authentication error when backing up hangfire collections. I tracked it down to my Mongo user not having permission for `bypassDocumentValidation`. My user has the default `readWrite` role for my hangfire database. The only other roles that have `bypassDocumentValidation` out of the box are `dbAdmin` and `restore`.

https://github.com/sergeyzwezdin/Hangfire.Mongo/blob/a4bb237a060a8003461b0f2ed89a924f49e88fff/src/Hangfire.Mongo/Migration/Strategies/Backup/CollectionMongoBackupStrategy.cs#L83-L88

I know this isn't a bug, though it might be worthwhile doing one of the following to prevent the same issue for users in future:
1. Clearly state in the doc that the `bypassDocumentValidation` permission is required for the `CollectionMongoBackupStrategy`
2. If document validation isn't needed, remove that constraint from the aggregation. I can't see anywhere in the source that requires the backup collection to have validation.

**Comment by gottscj** [comment]
@twgraham,

Thank you for your insights. I will try to remove it.
