### ISSUE TITLE
Add PrepareSchemaIfNecessary option

### ISSUE THREAD

**Issue by braca** [sergeyzwezdin/Hangfire.Mongo#256]
Hi,

It would be possible to add a `PrepareSchemaIfNecessary` option (where the default could be true), that when set to `false` `MongoStorage` ctor wouldn't try to do any migration? (similar to what the `Hangfire.SqlServerStorage` does).

Currently, if MongoDB goes down after the service has been initialized, as soon as MongoDB is up again, the server recovers as expected.

But if MongoDB is down when the service is starting, an exception is thrown during service initialization (because `MongoMigrationManager.MigrateIfNeeded` is executed) and the service won't start.

This can be problematic in some environments such as k8s.

I can open a PR for this if you would like to.

Thanks

**Comment by gottscj** [comment]
@braca,

Yes, off course, I will make this functionality overridable, so you create a class inheriting MongoStorage and you can override the needed functionality.

**Comment by gottscj** [comment]
fixed in v.07.17
