### ISSUE TITLE
How to get the list of executed jobs?

### ISSUE THREAD

**Issue by flabioassuncao** [sergeyzwezdin/Hangfire.Mongo#260]
I need to get the date of the lasts executed jobs. Is it possible?

**Comment by flabioassuncao** [comment]
var monitoringApi = JobStorage.Current.GetMonitoringApi();
var lastExecuted = monitoringApi.SucceededJobs(0, 2);

**Comment by gottscj** [comment]
@flabioassuncao ,

Sorry I didnt reply, its a bit busy at my end. thanks for posting this!
