### ISSUE TITLE
Reset running jobs

### ISSUE THREAD

**Issue by sunch1ld** [sergeyzwezdin/Hangfire.Mongo#261]
H therei,
I have an issue,I am using .NET core 2.1 with latest version of Hangfire.Mongo,
when I run some background jobs in a WebApi application they go in "Processing" state using a lot of cpu, in this phase I stop the application and reboot it.  In the boot phase these jobs remains in Processing phase, I would like they do no not restart and set them to deleted state,
How could I program this operation?

Thanks

**Comment by gottscj** [comment]
@sunch1ld,

sorry for the late reply. You should use the filters provided by the hangfire.core lib:
https://docs.hangfire.io/en/latest/extensibility/using-job-filters.html

hope this helps.

**Comment by gottscj** [comment]
@sunch1ld,

Did you solve your issue? It would be great if you could share if you got it solved :)
