### ISSUE TITLE
Multiple Processing in one job

### ISSUE THREAD

**Issue by jieke-wang** [sergeyzwezdin/Hangfire.Mongo#263]
I use hangfire 1.7.17, Hangfire.Mongo 0.7.17, asp.net net5.0, MongoDB 4.4.1 Single Node in docker(19.03.13)

However, there are multiple processing for the same task in the dashboard, I don't know what happened

Who can help me

![2020-12-23_163140](https://user-images.githubusercontent.com/12584587/102976379-6e8caf00-453c-11eb-9e99-8cbeed1bf080.png)

**Comment by jieke-wang** [comment]
There's no problem with short-term tasks, but with asynchronous or long-term tasks

**Comment by gottscj** [comment]
@jieke-wang,

Would you be able to paste your worker code? I need more info to be able to help

**Comment by jieke-wang** [comment]
ok, of course, Sorry to reply so late

In Startup class on ConfigureServices method, when AddHangfire:

`configuration.UseMongoStorage(Configuration["MongoConnectionString"], new MongoStorageOptions
{
	Prefix = "hangfire.mongo",
	CheckConnection = true,
	QueuePollInterval = TimeSpan.FromSeconds(5),
	InvisibilityTimeout = TimeSpan.FromSeconds(5),
	DistributedLockLifetime = TimeSpan.FromSeconds(5),
	MigrationOptions = new MongoMigrationOptions
	{
		MigrationStrategy = new MigrateMongoMigrationStrategy(),
		BackupStrategy = new CollectionMongoBackupStrategy()
	}
});`


In my BackgroundService:
`protected override async Task ExecuteAsync(CancellationToken stoppingToken)
{
	await Task.Delay(1);
	RecurringJob.AddOrUpdate<DemoJob>("Job1", job => job.Run(null, "Job1"), "* * * * *");
	RecurringJob.AddOrUpdate<DemoJob>("Job2", job => job.Run(null, "Job2"), "* * * * *");
}`

DemoJob:
`[DisableConcurrentExecution(20)]
public class DemoJob
{
	public void Run(PerformContext context, string jobName)
	{
		int retryCount = context.GetJobParameter<int>("RetryCount");
		var api = context.Storage.GetMonitoringApi();
		var job = api.JobDetails(context.BackgroundJob.Id);
		Console.WriteLine($"retryCount: {retryCount}");
		Console.WriteLine($"{jobName}, {DateTime.Now}");
		Console.WriteLine(Newtonsoft.Json.JsonConvert.SerializeObject(job.History));
		Thread.Sleep(10000);
	}
}`

**Comment by gottscj** [comment]
@jieke-wang,

Thanks! I'll try to re-produce

**Comment by gottscj** [comment]
@jieke-wang,

The jobs are not running but the state is changing only, from hangfire forum:
https://discuss.hangfire.io/t/disableconcurentexecution-does-not-appear-to-work/158

> The DisableConcurrentExecutionAttribute is working fine, but there is some misunderstanding I want to eliminate. This class is a server filter that works during the job processing stage. So, the dashboard shows you that background jobs are being processed. But at the same time only one of your background job methods is being executed – other method executions are waiting for a distributed lock.

You can combine your attribute with [AutomaticRetry(Attempts = 0)] if you want the abandon the queued job.

I hope this helps.

**Comment by gottscj** [comment]
closing
