### ISSUE TITLE
Jobs are not cleaned once expected

### ISSUE THREAD

**Issue by ollie10** [sergeyzwezdin/Hangfire.Mongo#265]
Hello,

I'm using Hangfire with Mongo as storage, I'm trying to remove suceded jobs after 6 hours they are completed for doing this I'm trying in both ways adding the parameter **JobExpirationCheckInterval = TimeSpan.FromHours(6)**, of **MongoStorageOptions** and using a Global Filter:

```
GlobalJobFilters.Filters.Add(new Services.Attributes.JobExpirationAttribute());

public class JobExpirationAttribute : JobFilterAttribute, IApplyStateFilter
{
	public void OnStateUnapplied(ApplyStateContext context, IWriteOnlyTransaction transaction)
	{
		context.JobExpirationTimeout = TimeSpan.FromHours(6);
	}

	public void OnStateApplied(ApplyStateContext context, IWriteOnlyTransaction transaction)
	{
		context.JobExpirationTimeout = TimeSpan.FromHours(6);
	}
}
```

Nothing seems to work, any clue? Many thanks

**Comment by gottscj** [comment]
@ollie10,

im not sure about the filters. You have to ask @odinserj in the Hangfire project: 
https://github.com/HangfireIO/Hangfire

It seems jobs expiry is hardcoded to 30 days. You might need to update the field after it has been added. But check the experts maintaining hangfire core. :)

https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/Client/CoreBackgroundJobFactory.cs

You can override the default behavior in hangfire.mongo by overriding the "CreateExpiredJob" method in the MongoConnection class:
https://github.com/sergeyzwezdin/Hangfire.Mongo/blob/master/src/Hangfire.Mongo/MongoConnection.cs
you also need to override the "MongoFactory" class and use that instance in the storageoptions.
 https://github.com/sergeyzwezdin/Hangfire.Mongo/blob/master/src/Hangfire.Mongo/MongoFactory.cs

Let me know if it works out.

**Comment by gottscj** [comment]
@ollie10,

I hope i worked out. closing this issue as it seems stale
