### ISSUE TITLE
Enhancement request: Migrate code to .Net 5 and remove Newtonsoft.Json dependency

### ISSUE THREAD

**Issue by Sonic198** [sergeyzwezdin/Hangfire.Mongo#269]
Do you have any plans to migrate code to .Net 5 and remove Newtonsoft.Json dependency which I think can be replaced by System.Text.Json?

Thanks,
Szymon

**Comment by gottscj** [comment]
@Sonic198,

Thank you for your request. 
We are targeting netstandard2.0, which is compatible with net5. If you reference this project from a net5 project the net5 runtime will be used.

we are only using NewtonSoft for logging, so its a good candidate to remove. good call. Hangfire.Core uses NewtonSoft though so you still depend on it though, sorry. :)
My personal reference is still Newtonsoft though as it has a lot of features not available in System.Text.Json yet. But We shouldnt need to depend on it in Hangfire.Mongo
