### ISSUE TITLE
Monitoring api JobDetails uses the internal mongo is instead of the jobId

### ISSUE THREAD

**Issue by BrunoVT1992** [sergeyzwezdin/Hangfire.Mongo#270]
Hi,

I am creating new recurring jobs with a custom id (for ex: "MyId-1234"). This work but when I want to query the monitroing api like below I get the exception: {"'MyId-12347' is not a valid 24 digit hex string."}.

IMonitoringApi monitoring = JobStorage.Current.GetMonitoringApi();
                JobDetailsDto details = monitoring.JobDetails("MyId-1234");

If I go look in the source code it is because the mongo implementation tries to convert this to a ObjectId and tries to query the internal id instead of the JobId (this happens in multiple places). Please fix this as this is breaking for us.

https://github.com/sergeyzwezdin/Hangfire.Mongo/blob/master/src/Hangfire.Mongo/MongoMonitoringApi.cs#L75

Kind regards

**Comment by gottscj** [comment]
@BrunoVT1992,

Thank you for your comment. I will take a look.
Thanks

**Comment by gottscj** [comment]
@BrunoVT1992,

Custom ids of the DTO's would be to much work to support. 
Could this option cover your use-case?
https://discuss.hangfire.io/t/how-to-set-custom-name-to-jobid/4161/4
it uses the [StorageConnectionExtensions](https://github.com/HangfireIO/Hangfire/blob/3c6d893023d5d7558d6098e80034865004b73786/src/Hangfire.Core/Storage/StorageConnectionExtensions.cs) extensions found in Hangfire.Core

Let me know if it works out.
Thanks

**Comment by BrunoVT1992** [comment]
@gottscj yes this worked for me. Thank you for the quick response.

**Comment by gottscj** [comment]
@BrunoVT1992,

glad to hear it! :)
