### ISSUE TITLE
how to detect no enqueue jobs from mongo db?

### ISSUE THREAD

**Issue by kenyeung128** [sergeyzwezdin/Hangfire.Mongo#274]
hi, We want to create a script to delete all databases with 0 enqueued jobs, how would you suggest we do that via database queries?

The Hangfire has a DB structure like below but no idea how to query in order to see if it's 0 enqueued jobs. Thanks.

![image](https://user-images.githubusercontent.com/7574094/113470344-7aff9c80-9487-11eb-9427-e4635786a3a8.png)

**Comment by gottscj** [comment]
@kenyeung128,

Deleting hangfire mongo dbs or collections on a running system could lead to an unstable system.

You can count the JobQueryDto's like so:

```javascript
{_t: "JobQueueDto"}
```
Hope this helps

**Comment by kenyeung128** [comment]
ok thanks a lot @gottscj
