### ISSUE TITLE
Too many queues to execute ??

### ISSUE THREAD

**Issue by one0410** [sergeyzwezdin/Hangfire.Mongo#277]
In mongod.log file, I find a lot of hangfire executions every 15 seconds. It seems to many.

![image](https://user-images.githubusercontent.com/11656628/114502771-e2270900-9c5e-11eb-9e58-2923b59d5be0.png)

![image](https://user-images.githubusercontent.com/11656628/114502934-1dc1d300-9c5f-11eb-88d8-79a3a23bff26.png)

![image](https://user-images.githubusercontent.com/11656628/114502974-2e724900-9c5f-11eb-8029-f8161b3def68.png)

I don't know if this holds the mongodb. Because sometimes other applications couldn't query database .

And you can see that almost 99% query are all related to hangfire .
![image](https://user-images.githubusercontent.com/11656628/114505145-865e7f00-9c62-11eb-95a0-a4953a64a489.png)

**Comment by gottscj** [comment]
@one0410,

thanks for posting. You can configure hangfire poll times in the options you give. "QueuePollInterval" will determine when the db is polled per worker.
default value is 15 seconds. eg. if you have 20 workers they will check the db for jobs each 15s.
The jobs are defined in its own collections which doesnt have influence on other collections. also they are reads which does not lock documents. looking at the logs provided, mongo doesnt seem overwhelmed though.

Things to try:
- You should define the jobs in its own db. just so they are completely separate from you business logic. this doesnt effect performance.
- You can set "QueuePollInterval" to 1 minute.
- You can disable notifications by setting "UseNotificationsCollection" to false. this will disable the tailable cursor listening for queued jobs.

hope this helps. :)

**Comment by one0410** [comment]
@gottscj Thank you for your quickly response.
I have another question. 
I only have 2 jobs defined. But why there are almost 20 concurrent queries running ???
Do I do something wrong ??

**Comment by gottscj** [comment]
@one0410,

You can specify the worker counter in the backgroundworker options provided by Hangfire.Core:
the default value is set to: Math.Min(Environment.ProcessorCount * 5, 20); 

hope this helps :)

**Comment by gottscj** [comment]
closing
