### ISSUE TITLE
Not executing any job "Hangfire.Mongo" using a lot of CPU

### ISSUE THREAD

**Issue by pughua** [sergeyzwezdin/Hangfire.Mongo#284]
Thank you very much for your work. I have a choice on Ubuntu.

The environment:
1.dotnet core 3.1
2.windows 10 or ubuntu 20
3.Hangfire.Mongo 0.7.22
4.Configuration code
`
var migrationOptions = new MongoMigrationOptions
                {
                    MigrationStrategy = new Hangfire.Mongo.Migration.Strategies.DropMongoMigrationStrategy(),
                    BackupStrategy = new Hangfire.Mongo.Migration.Strategies.Backup.NoneMongoBackupStrategy()
                };
                var storageOptions = new MongoStorageOptions
                {
                    // ...
                    MigrationOptions = migrationOptions
                };
                var mongoStorage = new MongoStorage(
                    MongoDB.Driver.MongoClientSettings.FromConnectionString(this.connectionString)
                    , this.dbName
                    , storageOptions);
                GlobalConfiguration.Configuration.UseStorage(mongoStorage);
`
`
var server = new BackgroundJobServer(new BackgroundJobServerOptions
            {
                Queues = new string[]{"test"},
                TaskScheduler = null
            }); 
`

The step:
1.No Jobs were created.After starting the application for a while, I found that CPU usage was above 90%.
2.Use the diagnostic tool of VS to view, as shown in the following figure
![image](https://user-images.githubusercontent.com/780726/124568415-76c49000-de77-11eb-827f-e8b8105bb1a5.png)

**Comment by pughua** [comment]
Repeat steps:
1. set MongoMigrationOptions.UseNotificationsCollection = true
2. Start multiple BackgroundJobServer
3. When the parameter "queues" in method "JobQueueSemaphore.WaitAny" does not contain the parameter "queue" in method "JobQueueSemaphore.Release". "_releasedSignal" does not block threads

**Comment by gottscj** [comment]
@pughua,

Thanks! I'll take a look.

**Comment by gottscj** [comment]
@pughua,

Just letting you know, I didnt have time to look at this yet, so a fix wont make into next release (v0.7.24), but I will add it for the following.

Thanks,

**Comment by pughua** [comment]
@gottscj 
Looking forward to your release.
