### ISSUE TITLE
Specifying databaseName in MongoBootstrapperConfigurationExtensions

### ISSUE THREAD

**Issue by forbeshawkins** [sergeyzwezdin/Hangfire.Mongo#285]
Thanks for this library!

I noticed that you have deprecated the UseMongoStorage overload with the databaseName parameter, in favour of providing the database name in the connection string.

According to https://docs.mongodb.com/manual/reference/connection-string, specification of the database name in the connection string is (a) still entirely optional, and (b) if specified, it is intended to be

"the authentication database to use if the connection string includes username:password@ authentication credentials but the authSource option is unspecified"

In this case, we are specifying the name of the database for storing job information, not for authentication.

Is there a good reason for preferring the providing of the database name in the connection string? Or should the obsolete attribute be removed from the UseMongoStorage overload perhaps?

**Comment by gottscj** [comment]
Hi,

 dont recall why we made it obsolete. ¯\_(ツ)_/¯

We can remove it again. no problem

**Comment by forbeshawkins** [comment]
Awesome - thanks
