### ISSUE TITLE
JobId Index speedup

### ISSUE THREAD

**Issue by lukasroberts** [sergeyzwezdin/Hangfire.Mongo#29]
Hey

I have noticed that adding indexes for the collections state, jobParameter, and jobQueue has helped speed up performance.

I have created these indexes within HangfireDbContext via something like this:

```

public HangfireDbContext(MongoDatabase database)
        {
            Database = database;
            ConnectionId = Guid.NewGuid().ToString();
            CreateJobIndexes();
        }

        private void CreateJobIndexes()
        {
            // create for jobid on state, jobParameter, jobQueue
            State.CreateIndex(IndexKeys<StateDto>.Descending(p => p.JobId));
            JobParameter.CreateIndex(IndexKeys<JobParameterDto>.Descending(p => p.JobId));
            JobQueue.CreateIndex(IndexKeys<JobQueueDto>.Descending(p => p.JobId));
        }

```

Do you think this change should be included? It ensures these indexes are created automatically and helps performance for me. On the other hand some people may not want these indexes. What are your thoughts?

**Comment by sergeyzwezdin** [comment]
Hi Lukas

Thank you very much. I think it's pretty reasonable. Could you please create PR for this?

**Comment by MarLoe** [comment]
@lukasroberts, I will consider this issue implemented. Please upgrade to Hangfire.Mongo ver. 0.2.8 to take advantage of this.
