### ISSUE TITLE
Return id from GetAllEntriesFromHash method instead of key or both

### ISSUE THREAD

**Issue by iamgurdip** [sergeyzwezdin/Hangfire.Mongo#32]
when i call the GetAllEntriesFromHash() method it returns the Key (Job Name) as the id, which causes an issue when trying to call GetStateData() which requires an Id not the Key. So currently there is not way to get the state data b/c id is unknown.

**Comment by sergeyzwezdin** [comment]
How it's implemented in SQL storage?

**Comment by gottscj** [comment]
We cannot change this. You need to submit a ticket in the HangFire github page.

Closing this.
