### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by chadit** [sergeyzwezdin/Hangfire.Mongo#33]
Hangfire v1.5.5
Hangfire.Mongo v0.2.5

I get this error "An item with the same key has already been added" when I restart my web application and RecurringJob.AddOrUpdate(... is called.  Memory and SQL providers do not throw this error.

**Comment by sergeyzwezdin** [comment]
@chadit thank you for you report. Could you provide complete steps to reproduce the issue?

**Comment by MarLoe** [comment]
@chadit, I cannot reproduce this issue. Please upgrade to Hangfire.Mongo ver. 0.2.8 and see if you still have this issue. If you do, please comment on this issue or create a new one.
