### ISSUE TITLE
DisableConcurrentExecution attribute cannot support? 

### ISSUE THREAD

**Issue by icsharp** [sergeyzwezdin/Hangfire.Mongo#37]
It works well when using sqlserver storage, only one job can be executed at a time.
I try it to use Mongo storage,it does not work...

**Comment by sergeyzwezdin** [comment]
when it added to HangFire?

**Comment by icsharp** [comment]
@sergeyzwezdin 
when my hangfire server started,I added it to recurringjob ,code as below:
`public interface ISampleService : IAppService
	{
		/// <summary>
		/// Job Test
		/// </summary>
		[DisableConcurrentExecution(600)]
		[AutomaticRetry(Attempts = 3)]
		[DisplayName("Job Test")]
		[Queue("default")]
		void Test();
	}`

`RecurringJob.AddOrUpdate<ISampleService>(x => x.Test(), "*/5 * * * *", TimeZoneInfo.Local);`

**Comment by icsharp** [comment]
@sergeyzwezdin 
it is the same issuse to https://github.com/sergeyzwezdin/Hangfire.Mongo/issues/15

**Comment by sergeyzwezdin** [comment]
I guess `DisableConcurrentExecution` appeared in hangfire after initial release of hangfire.mongo.
You can make PR if you need it asap, or wait until I have time for this :-)

**Comment by icsharp** [comment]
@sergeyzwezdin 
I host hangfire server in windows service, you can test if you have time,thanks for you reply.

**Comment by sergeyzwezdin** [comment]
> You can make PR if you need it asap, or wait until I have time for this :-)

:-)

**Comment by icsharp** [comment]
@sergeyzwezdin 
``` csharp
 // Check lock
                DateTime lockTimeoutTime = DateTime.Now.Add(timeout);
                bool isLockedBySomeoneElse;
                bool isFirstAttempt = true;
                do
                {
                    isLockedBySomeoneElse = database.DistributedLock
                            .Find(Builders<DistributedLockDto>.Filter.Eq(_ => _.Resource, resource) &
                                  Builders<DistributedLockDto>.Filter.Ne(_ => _.ClientId, _options.ClientId))
                            .FirstOrDefault() != null;

                    if (isFirstAttempt)
                        isFirstAttempt = false;
                    else
                        Thread.Sleep((int)timeout.TotalMilliseconds / 10);
                }
```
I find the ```do ....while ``` loops is always done only one times,so  the condition ```isLockedBySomeoneElse``` maybe is not right,and need to be changed filter ```Builders<DistributedLockDto>.Filter.Ne(_ => _.ClientId, _options.ClientId)``` to ```Builders<DistributedLockDto>.Filter.Eq(_ => _.ClientId, _options.ClientId)```

**Comment by MarLoe** [comment]
I observe this issue as well. I believe it is related to a faulty implemented MongoDistributedLock. I have made a pull request with a fix:
https://github.com/sergeyzwezdin/Hangfire.Mongo/pull/40

**Comment by MarLoe** [comment]
The Hangfire attribute DisableConcurrentExecution relies heavily on the implementation of JobStorageConnection.AcquireDistributedLock 
With the merge of pull request #40 that fixes MongoDistributedLock I believe this issue is resolved.
