### ISSUE TITLE
Asp.Net Core compatibility

### ISSUE THREAD

**Issue by tmm360** [sergeyzwezdin/Hangfire.Mongo#38]
Hangfire 1.6.0 has introduced compatibility with Asp.Net Core. Do you have plans for .Net Core support?

**Comment by sergeyzwezdin** [comment]
Mongo driver (which is used in Hangfire.Mongo) [have no .NET Core support yet](https://jira.mongodb.org/browse/CSHARP-1177).
Will keep this issue opened for possible future support.

**Comment by gzpbx** [comment]
https://www.nuget.org/packages/MongoDB.Driver/2.3.0-beta1

**Comment by pieceofsummer** [comment]
I have posted a PR #39 adding .NET Core support with beta driver, you're welcomed to try it out.

**Comment by kroniak** [comment]
@pieceofsummer rc1 of 2.3.0 driver was released. Please update a PR.

**Comment by pieceofsummer** [comment]
@kroniak I believe there's currently no need for that. 

According to semantic versioning, it will use the latest version (rc1) anyway, but updating min version to `2.3.0-rc1` will block any local builds.

Let's wait for the official release first.

**Comment by pieceofsummer** [comment]
Updated PR to a 2.3.0 release. But not in the mood to work out MSBuild's newly-introduced quirks, so validation doesn't pass.

**Comment by Vaiune** [comment]
When could we get this? Definitely looking to try it out.

**Comment by gottscj** [comment]
I agree, especially if Hangfire.Core supports it. It doesnt build though.
Martin, you have had some communication with "peaceofsummer" ? what do you
think?

**Comment by stanislavromanov** [comment]
@pieceofsummer Mongo driver 2.3 is out, any news?

**Comment by Andrew-Brad** [comment]
Also looking forward to this!  Many thanks for everyone's efforts!

**Comment by dsoronda** [comment]
Can you please fix this issue ? I would like to use Hangfire on DotNet Core with MongoDb as backend. Thanks

**Comment by MarLoe** [comment]
Please checkout PR #49

**Comment by MarLoe** [comment]
Release 0.3.0 includes .NET Standard 1.5 support.

**Comment by adsamcik** [comment]
Package Hangfire.Mongo 0.3.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Hangfire.Mongo 0.3.0 supports: net45 (.NETFramework,Version=v4.5)

**Comment by MarLoe** [comment]
@adsamcik, thank you for your feedback.

You are absolutely right! Someone forgot to include the .NET Standard 1.5 libraries in the NuGet. The responsible person has been identified and according to our CDD (Cake Driven Development) he will bring cake tomorrow.

A new NuGet 0.3.1 has been released. Please update and let us know how it works.

@marloe remember to bring cake.

**Comment by adsamcik** [comment]
@MarLoe It looks happy, thanks :)

**Comment by jocutajar** [comment]
Hi, anyone has a working example of a dotnet core project.json? Thanks a bunch.

**Comment by stanislavromanov** [comment]
@jocutajar I use my own fork of this project which supports .net core. https://www.nuget.org/packages/Stan.Hangfire.Mongo/

Obv this is not best solution and I plan to switch back to official as soon as it supports .net core.

**Comment by MarLoe** [comment]
@jocutajar, @stanislavromanov, We should be supporting .net core. Please let me know what is missing/failing in order for us to support .net core correctly.

Thanks in advance

**Comment by stanislavromanov** [comment]
Oh ok, thanks.

**Comment by MarLoe** [comment]
@jocutajar, @stanislavromanov, As of v0.3.1 we supported .net core and as of v0.3.2 we support .net core on unix platforms as well.

**Comment by MarLoe** [comment]
@jocutajar, Have you checked out the .net core sample in this repo?

[Hangfire.Mongo.Sample.NETCore](https://github.com/sergeyzwezdin/Hangfire.Mongo/tree/master/src/Hangfire.Mongo.Sample.NETCore)

**Comment by jocutajar** [comment]
@MarLoe , thanks, lovely. I was bitten by the v 1.0.0 trouble.
