### ISSUE TITLE
Enqueuing large number of jobs keep in "awaiting" state

### ISSUE THREAD

**Issue by gofix** [sergeyzwezdin/Hangfire.Mongo#41]
Using Hangfire.Mongo 0.2.6:
- We're queuing some jobs (130) in a very short time;
- The jobs keep in "Awaiting" state, nothing happens;
- New jobs can be added, nothing happens;

Same scenario seems to work just fine with SqlServer (but we have to deal with a customer using Oracle here, that's why we chose the Hangfire.Mongo scenario), and a smaller queue (28, for example) doesn't expose this problem.

**Comment by gofix** [comment]
FYI, we're now using https://www.nuget.org/packages/Hangfire.Mongo.MarLoe, in which this very problem seems to be solved (nice work https://www.nuget.org/profiles/MarLoe)

**Comment by MarLoe** [comment]
Well, thank you @gofix 
Since pull request #40 has been merged in, I will close this issue.
