### ISSUE TITLE
Cannot get jobs due to KeyNotFoundException

### ISSUE THREAD

**Issue by kienct89** [sergeyzwezdin/Hangfire.Mongo#51]
## Environment:

- .NET framework 4.6.1
- MongoDB.Driver 2.3.0
- Hangfire.Mongo 0.3.1
- Hangfire.Core 1.6.7

## Setup Code:

```
Hangfire.GlobalConfiguration.Configuration.UseMongoStorage(applicationSettings.MongoConnectionString,applicationSettings.MongoDbName);
app.UseHangfireServer();
app.UseHangfireDashboard();
BackgroundJob.Enqueue(() => Console.WriteLine("Fire-and-forget!"));
```

## Data in database:

Job:

```
{
    "_id": 7,
    "StateId": "584508cf4f5f31a300ab1af3",
    "StateName": "Succeeded",
    "InvocationData": "{\r\n  \"type\": \"System.Console, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\",\r\n  \"method\": \"WriteLine\",\r\n  \"parameterTypes\": \"[\\r\\n  \\\"System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\\\"\\r\\n]\",\r\n  \"arguments\": \"[\\r\\n  \\\"\\\\\\\"Fire-and-forget!\\\\\\\"\\\"\\r\\n]\"\r\n}",
    "Arguments": "[\r\n  \"\\\"Fire-and-forget!\\\"\"\r\n]",
    "CreatedAt": "2016-12-05 14:27:19",
    "ExpireAt": "2016-12-06 14:27:27"
}
```

State:

```
{
    "_id": "584508cf4f5f31a300ab1af3",
    "JobId": 7,
    "Name": "Succeeded",
    "Reason": null,
    "CreatedAt": "2016-12-05 14:27:27",
    "Data": "{\r\n  \"succeededAt\": \"2016-12-05T06:27:27.1272919Z\",\r\n  \"performanceDuration\": \"0\",\r\n  \"latency\": \"7327\"\r\n}"
}
```

## Error details:

```
[KeyNotFoundException: The given key was not present in the dictionary.]
   System.Collections.Generic.Dictionary`2.get_Item(TKey key) +12465717
   Hangfire.Mongo.<>c.<SucceededJobs>b__11_1(JobDetailedDto sqlJob, Job job, Dictionary`2 stateData) in C:\projects\hangfire-mongo\artifacts\sources\Hangfire.Mongo\MongoMonitoringApi.cs:212
   Hangfire.Mongo.MongoMonitoringApi.DeserializeJobs(ICollection`1 jobs, Func`4 selector) in C:\projects\hangfire-mongo\artifacts\sources\Hangfire.Mongo\MongoMonitoringApi.cs:374
   Hangfire.Mongo.MongoMonitoringApi.GetJobs(HangfireDbContext connection, Int32 from, Int32 count, String stateName, Func`4 selector) in C:\projects\hangfire-mongo\artifacts\sources\Hangfire.Mongo\MongoMonitoringApi.cs:488
   Hangfire.Mongo.<>c__DisplayClass11_0.<SucceededJobs>b__0(HangfireDbContext connection) in C:\projects\hangfire-mongo\artifacts\sources\Hangfire.Mongo\MongoMonitoringApi.cs:211
   Hangfire.Mongo.MongoMonitoringApi.UseConnection(Func`2 action) in C:\projects\hangfire-mongo\artifacts\sources\Hangfire.Mongo\MongoMonitoringApi.cs:316
   Hangfire.Mongo.MongoMonitoringApi.SucceededJobs(Int32 from, Int32 count) in C:\projects\hangfire-mongo\artifacts\sources\Hangfire.Mongo\MongoMonitoringApi.cs:211
```

**Comment by gottscj** [comment]
Hi @kienct89,

Looking at your "State" data, it seems that the "Data" object is in Camel-Case instead of Pascal-Case. 
I can see that "succeededAt", should be reflected as "SucceededAt" in your mongo db.

Do you have a special serializer configuration?

**Comment by kienct89** [comment]
@gottscj : hi gottscj, I didn't specify the `ContractResolver` in my `JobHelper.SerializerSettings`

here's my setup code

```
JobHelper.SetSerializerSettings(new JsonSerializerSettings
{
    NullValueHandling = NullValueHandling.Ignore,
    ReferenceLoopHandling = ReferenceLoopHandling.Ignore
});
```

**Comment by MarLoe** [comment]
@kienct89, I just tried to reproduce with this config:

`JobHelper.SetSerializerSettings(new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore,
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
                ContractResolver = new CamelCasePropertyNamesContractResolver()
            });`

This will expose the error you are seeing. From your dump of "State" it is clear that you (at some point) used camel-casing. Please try to drop your Mongo collection, and try again. If you still see "State->Data" written with camel-case in Mongo, you must investigate your code to resolve why this is happening.

When that is  said, it is clear that Hangfire.Mongo should be able to handle this in a better way. Reading @odinserj 's code for SqlServer storage, I see the very same problem. @odinserj Perhaps exposing the JsonSerializerSettings used by JobHelper, so we can run the property names through that. Or should we just not use the JobHelper when serializing to/from Dictionary<string, string>?

/Martin

**Comment by kienct89** [comment]
@MarLoe @gottscj thanks for your help, I'm able to resolve it by overriding the `ContractResolver` to the `DefaultContractResolver`

JobHelper.SetSerializerSettings(new JsonSerializerSettings
{
    NullValueHandling = NullValueHandling.Ignore,
    ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
    ContractResolver = new DefaultContractResolver()
});
