### ISSUE TITLE
Hangfire.Mongo vs Hangfire.Sql

### ISSUE THREAD

**Issue by adsamcik** [sergeyzwezdin/Hangfire.Mongo#54]
I'll keep this updated if I find more. _Everything tested under asp.net core 1.1 on ubuntu._

- History graph works really weirdly. It almost seems it doesn't remember anything.
- Follow up jobs (Continuations) are enqueued as new jobs and are put at the end of the queue, in sql they get executed right after the original job is done.
- Jobs don't disappear right away from queue when deleted. 
- Jobs in dashboard show 0 when no items are in queue but some are still being processed (Not too sure about this one, but it should show the number of jobs that are being processed imo)

**Comment by gottscj** [comment]
Hi @adsamcik, sorry for the late reply, any news on this? :)

**Comment by adsamcik** [comment]
I have kept it updated and I have been meaning to try and improve some of it, but unfortunately I am quite busy lately. Maybe in a month or two.

**Comment by gottscj** [comment]
@adsamcik,

 #121 should fix the dashboard issues. Did you have had any chance to test this with newer releases?

Thanks!

**Comment by adsamcik** [comment]
@gottscj Sorry I had to change database because of platform compatibility issues and I don't have any project where I could test it properly at the moment.

**Comment by gottscj** [comment]
history graph is fixed in #121 - closing
