### ISSUE TITLE
v 1.0.0 breaks nuget dependencies in dotnet core with full framework, worked in 0.3.2

### ISSUE THREAD

**Issue by jocutajar** [sergeyzwezdin/Hangfire.Mongo#55]
This builds:
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": {
    "Hangfire.AspNetCore": "1.6.8",
    "Hangfire": "1.6.8",
    "Hangfire.Core": "1.6.8",
    "HangFire.Mongo": "0.3.2",
    "Common.Logging": "2.2.0",
    "Common.Logging.Core": "2.2.0"
  },
  "frameworks": {
    "net461": {
    }
  }
}
```
This fails:
```
    "HangFire.Mongo": "1.0.0",
```
With 
> ...\project.json(11,29): error NU1001: The dependency HangFire.Core >= 1.2.2 could not be resolved.

I suspect case sensitive names to be the culprit:
- Hangfire.AspNetCore.dll
- Hangfire.Core.dll
- Hangfire.Mongo.dll
- Hangfire.SqlServer.dll

**Comment by MarLoe** [comment]
@jocutajar I need a bit more info to catch up with what you are experiencing.

Hangfire.Mongo is currently at version 0.3.2, so referencing 1.0.0 will obviously fail.

**Comment by MarLoe** [comment]
@jocutajar according to your comment on #38, this issue seems not to be relevant. Please close it or leave a comment that is can be closed, if you feel that your issue has been resolved.

**Comment by MarLoe** [comment]
@jocutajar, will close this issue. Please reopen if you feel you issue has net been resolved.
