### ISSUE TITLE
E11000 duplicated key error writing schema version

### ISSUE THREAD

**Issue by vegar** [sergeyzwezdin/Hangfire.Mongo#58]
I think this might be a timing issue when starting multiple hangfire server instances at the same time.

[The code](https://github.com/sergeyzwezdin/Hangfire.Mongo/blob/master/src/Hangfire.Mongo/Database/HangfireDbContext.cs#L143-L147) does a 'Delete all->Insert one':

```
                if (RequiredSchemaVersion > schema.Version)
                {
                    Schema.DeleteMany(new BsonDocument());
                    Schema.InsertOne(new SchemaDto { Version = RequiredSchemaVersion });
                }
```

and I suspect that one instance will insert a new schema document after the second instance checks the version and before it inserts the doc. The result is two instances trying to insert a document with the same id.

Would it be possible to solve this by changing the insert to a upsert?

**Comment by gottscj** [comment]
Thanks,

Looks like a bug. I'll take a look.
