### ISSUE TITLE
Unusable after 15-30 enqueued jobs per second

### ISSUE THREAD

**Issue by ZOXEXIVO** [sergeyzwezdin/Hangfire.Mongo#62]
Sergey, i think, you test your provider with 10 jobs in day, but try to make some load to your provider with big arguments in jobs. 
After small load - system is unresponsible. Dashboard opening for minutes!
Enqueued jobs processed with 5-10 seconds per job. It's really bad

**Comment by gottscj** [comment]
@ZOXEXIVO,

Could you elaborate on how you produce this behavior?

If you run the sample you can start 1000 jobs via the hangfire dashboard? did you try this?

Thanks
Jonas

**Comment by gottscj** [comment]
@ZOXEXIVO,
 
Hangfire's worker count is 20, per default. If you start jobs which takes 10s to run in a loop, you will quickly exhaust your resources.

I added a branch: https://github.com/sergeyzwezdin/Hangfire.Mongo/tree/Issue%2362_BigSlowJobs
Does this mimic your setup?

On my workstation it finishes 100 long running (10s) jobs in 54989.3418 ms with 25 workers.

Hangfire is originally build with SQL in mind, so theres not much we can do about "RDMS mind". But if you have optimizations, we would love a PR. :)

**Comment by MarLoe** [comment]
@ZOXEXIVO,

Thank you for your feedback. Since we have not heard back from you, we assume you have gone different ways.
I will close this issue now. If you still think it as an issue worth pursuing, feel free to open/create issue and provide some more feedback.
