### ISSUE TITLE
State and JobParameter documents never get deleted

### ISSUE THREAD

**Issue by asciutto990** [sergeyzwezdin/Hangfire.Mongo#65]
I'm using MongoStorageOptions default values. I'm running on azure and my app is always on. Not one document has been deleted after the default expiration time. Is this a known issue or is there something else I need to configure?

**Comment by gottscj** [comment]
@asciutto990,

Looks like a bug to me. Do you know how the SqlStorage behaves?

Thanks,
Jonas

**Comment by asciutto990** [comment]
I haven't tested it out but as per it's documentation, successful jobs should be cleaned up upon expiration.

**Comment by gottscj** [comment]
Fixed with #66

**Comment by asciutto990** [comment]
Great! How long until this is available on NuGet?

**Comment by gottscj** [comment]
Not long. 
Please note this is introduces breaking changes which will require you to drop your jobs db.

We do have some other breaking changes we would like to introduce now, so we don't spread that out on multiple releases.
