### ISSUE TITLE
Logs are returned in the wrong order when using Hangfire.Console with Hangfire.Mongo

### ISSUE THREAD

**Issue by testos944** [sergeyzwezdin/Hangfire.Mongo#74]
When using Hangfire.Console, the messages are returned in no particular order. See relevant discussion on Hangfire.Console : https://github.com/pieceofsummer/Hangfire.Console/issues/36

When using PerformContext.WriteLine, the logs are often in the wrong order.

![console-wrong-log-order](https://user-images.githubusercontent.com/22033728/28009374-8b866408-655b-11e7-8f2a-7d2545478c86.png)

Current Setup : 

- Hangfire 1.6.14
- Hangfire.Console 1.3.3
- Hangfire.Mongo 0.4.0 
- Mongo Version : 3.0.12 on Windows

It seems okay when the first log appears, however when the job is finished it gets moved to the end of the paragraph.

It used to be on any log, however I can't seem to reproduce at the moment, now it's usually the first log that changes position.

**Comment by gottscj** [comment]
@testos944,

There is another bug in 0.4.0, where we dont write the full object set/list/hash/state to mongo. Its a bug in the C# driver. Please drop your jobs an update to 0.4.1.

I will make sure this is fixed in 0.4.2

Thanks

**Comment by testos944** [comment]
Thanks !
