### ISSUE TITLE
'Drop collection'-upgrade strategy from 3.x to 4.x - isn't that a little hash...?

### ISSUE THREAD

**Issue by vegar** [sergeyzwezdin/Hangfire.Mongo#76]
I was looking into updating the nuget package from 3.x to 4.x when I saw the following breaking change notice:

> *** BREAKING CHANGES FOR v0.4.0 *** (v0.4.0)
> ....
>
> What should I do?
>
> You have to drop your jobs db.

It might be me missing something here, but how on earth can we manage this?
So at some point in time we'll deploy new code into production. We cannot just drop the entire job queue at that point? 

So...

Can anyone explain to me what I might be missing, or share some experience on how to actually handle this in a running system?

**Comment by gottscj** [comment]
@vegar,
Thanks for your input.
Please know, we do this in our spare time, and our resources are limited.
Im not sure how you use Hangfire. But I would recommend you to make sure you dont have any jobs in the job queue, and then drop it at that point. You can use the dashboard to check this.
If this doesnt work for you, you have a couple of options.
1. Dont upgrade just yet. Add an enhancement request with your needs.
  - We will add it when we have time.
2. Create a migration step (we would love a PR with this)

Thanks

**Comment by vegar** [comment]
Of cause I understand the problem with sparetime and limited resources.

When it comes to how I use hangfire, I thought I used it like everybody else. In production, constantly queueing new tasks, both immediately and scheduled.

I'm not sure how we will go about the transition to the next version. If I come up with something clever, I'll let you know for sure. If anyone else has some ideas or experiences, I hope they share :-)

________________________________

**Comment by gottscj** [comment]
Ok. 
Another thing is that even though @odinserj has done done an amazing job with he's documentation for Hangfire, the documentation for the API is not documented and has been created by reverse engineering he's SQL implementation.
Creating a migration for DTO's we dont fully understand or have insight to (hash, set, list, hash etc.) also have implications as we might do more harm than good with a migration step. This is another reason we propose a "clean slate" (eg. no jobs in the jobQueue).
I will look into creating a migration step (when time allows), with the caveat that it might corrupt your jobs DB if I misunderstood something. :)

**Comment by vegar** [comment]
Sounds challenging :-)
I'll see if there is anything I can do to help when I'm back from vacation.
Don't sweat because of me, though. I'm sure we'll find away one day. We have already started planning replacing a lot of our scheduled task with recurring tasks. That would make things easier.

________________________________

**Comment by gottscj** [comment]
@vegar,

@MarLoe and I will look into a migration strategy. It wont make for the upcomming release (0.4.2), but it will be introduced in (0.4.3). We will target it so it should possible to upgrade from 0.3.2 to 0.4.3 using migrations.

Thanks,
Jonas

**Comment by MarLoe** [comment]
@vegar, we are working on a migration feature for Hangfire.Mongo. Please check out the migration branch if you want a sneak peek of this.

**Comment by MarLoe** [comment]
Migration will be a part of the next release. Please stay tuned ;)

**Comment by vegar** [comment]
Perfect! Nicely synchronized with the end of my vacation. :-)

________________________________
