### ISSUE TITLE
Element 'StateHistory' not found Exception from GetRecurringJobs()

### ISSUE THREAD

**Issue by lukpep** [sergeyzwezdin/Hangfire.Mongo#85]
`var recurringJobs = JobStorage.Current.GetConnection().GetRecurringJobs();`

And I get:

> System.Collections.Generic.KeyNotFoundException occurred
  HResult=0x80131577
  Message=Element 'StateHistory' not found.
  Source=Cannot evaluate the exception source
  StackTrace:
   at MongoDB.Bson.BsonDocument.get_Item(String name)
   at Hangfire.Mongo.MongoConnection.GetStateData(String jobId)
   at Hangfire.Storage.StorageConnectionExtensions.GetRecurringJobDtos(IStorageConnection connection, IEnumerable`1 ids)

I also get http 500 error on dashboard when I click "Recurring Jobs" tab but only after first execution of job. Before that tab is accesible.

My configuration:
```
services.AddHangfire((config) =>
{
	config.UseMongoStorage(mongoSettings.ConnectionString, mongoSettings.Database, new MongoStorageOptions {Prefix = "_hangfire_"});
	config.UseAutofacActivator(ApplicationContainer);
});
```

```
app.UseHangfireDashboard("/jobs", new DashboardOptions { Authorization = new[] { new DashboardAuthorizeFilter() }});
app.UseHangfireServer();
```

All jobs are working fine - I just have problem viewing them.

Hangfire 1.6.15
Hangfire.Autofac 2.3.1
Hangfire.Mongo 0.4.1

**Comment by lukpep** [comment]
It has something to do with naming conventions for mongo. Document in databse has field "stateHistory" not StateHistory. When I change it to "StateHistory" and all capitalize first letter in subdocuments it works

**Comment by lukpep** [comment]
I thing problem is in lines 211-213:
```
var state = latest[nameof(JobDto.StateHistory)]
                .AsBsonArray
                .FirstOrDefault();
```

nameof returns StateHistory instead of stateHistory and later same in: 

```
return new StateData
            {
                Name = state[nameof(StateDto.Name)] == BsonNull.Value ? null : state[nameof(StateDto.Name)].AsString,
                Reason = state[nameof(StateDto.Reason)] == BsonNull.Value ? null : state[nameof(StateDto.Reason)].AsString,
                Data = state[nameof(StateDto.Data)] == BsonNull.Value ? new Dictionary<string, string>() :
                    state[nameof(StateDto.Data)].AsBsonDocument.Elements.ToDictionary(e => e.Name, e => e.Value.AsString)
            };
```

It seems that mongo uses camelCase.

**Comment by lukpep** [comment]
It seems that mongo conventions are registered globally. In my app I use camelCase convention for field naming:

`new CamelCaseElementNameConvention()`

And that brokes usage of nameof function. 
I disabled this convention for Hangfire.Mongo assemblies:

`ConventionRegistry.Register("GalCloudConventions", new MongoConvention(), x => !x.AssemblyQualifiedName.Contains("Hangfire.Mongo"));`

But it's just a workaround - maybe some other method for obtaining fields from Mongo Document would be better (one that takes naming conventions into account)?

**Comment by MarLoe** [comment]
@lukpep, this casing issue seems to popup every now and then - causing great confusion.

So now we have decided to have Hangfire.Mongo take control. We will going forward ignore any naming convention and use our own hard coded names. that way we can avoid dealing with all sorts of naming conventions.

If interested, take a look at the [naming_convention](https://github.com/sergeyzwezdin/Hangfire.Mongo/tree/naming_convention) branch or PR #97. It will be a part of the upcoming 0.5.2 release.

**Comment by lukpep** [comment]
testing 0.5.2 and seems like it's working. Thanks :)
