### ISSUE TITLE
Element 'data' does not match any field or property of class Hangfire.Mongo.Dto.ServerDto.

### ISSUE THREAD

**Issue by axle-h** [sergeyzwezdin/Hangfire.Mongo#96]
Version 0.5.1 with a fresh database that has run a single background job and has two scheduled jobs queued.
Navigating to /jobs/processing or /servers results in:

System.FormatException: Element 'data' does not match any field or property of class Hangfire.Mongo.Dto.ServerDto.

Example document from the hangfire.server collection:

   {
       "_id" : "my-server-name",
       "data" : "{\"WorkerCount\":20,\"Queues\":[\"default\"],\"StartedAt\":\"2017-08-31T09:30:36.4062744Z\"}",
       "lastHeartbeat" : ISODate("2017-08-31T09:31:06.647Z")
   }

**Comment by MarLoe** [comment]
@axle-h , how do you configure your hangfire and hangfire.mongo? Do you use any custom serializers?
Looks some how like the same problem you reported in #95 

The dto's gets serialized with camelCase rather than the DefaultCase, leading to some deserialization problems.

**Comment by axle-h** [comment]
Thanks. The solution in issue #95 fixed this as I was using CamelCaseElementNameConvention.
Is support for this not possible? If not is there a way to check this at startup and throw something readable?

**Comment by MarLoe** [comment]
@axle-h , could you please copy/paste your setup that let to this issue? I am having a hard time reproducing this myself. And I would like to look into why this has such poor support.

Obviously, if you have been running with "mixed" naming conventions (e.g. first one and then changing it to another) then you are asking for trouble ;)

**Comment by axle-h** [comment]
@MarLoe I think it's a mixed case scenario like you said. We have an API running in the same application that uses also mongo. This is being called in the type constructor of our repository base class:

    ConventionRegistry.Register("camelCase", new ConventionPack
                                         {
                                             new CamelCaseElementNameConvention()
                                         }, x => true);

Obviously this is only called once the DI has fired up and started resolving stuff, which in our application happens after Hangfire initializes the database. I don't think there's anything that you can do short of documenting it... The perils of static configuration laid bare.

**Comment by axle-h** [comment]
This is essentially a duplicate of #85
